### PR TITLE
Fix TLS connection closure (source side)

### LINKED ISSUE #2703: Validation of TLS close_notify per RFC spec
# syslog-ng
I have a report that syslog-ng is not sending a response to a tls session's close_notify alert per RFC5425 4.4 spec: https://tools.ietf.org/html/rfc5425#section-4.4

A mutually authenticated TLS session can be closed by the sender with either TCP closure or close_notify. The transport shipper is rsyslog to our receiver, syslog-ng. rsyslog is reporting a connection error when syslog-ng does not properly respond with the close_notify alert response per RFC.

I'm wondering how to validate this as well as potentially log it, and correct it?

## Version of syslog-ng

```
syslog-ng 3 (3.20.1)
Config version: 3.20
Installer-Version: 3.20.1
Revision: 3.20.1-1
Compile-Date: Mar  1 2019 09:36:45
Module-Directory: /usr/lib/syslog-ng/3.20
Module-Path: /usr/lib/syslog-ng/3.20
Include-Path: /usr/share/syslog-ng/include
Error opening plugin module; module='mod-java', error='libjvm.so: cannot open shared object file: No such file or directory'
Available-Modules: hook-commands,stardate,csvparser,dbparser,afuser,add-contextual-data,graphite,riemann,tfgetent,geoip-plugin,afsocket,syslogformat,afsql,redis,disk-buffer,mod-python,pseudofile,afmongodb,pacctformat,affile,http,geoip2-plugin,confgen,basicfuncs,cryptofuncs,afstomp,xml,map-value-pairs,afamqp,kvformat,appmodel,sdjournal,examples,afprog,cef,afsmtp,date,system-source,json-plugin,snmptrapd-parser,tags-parser,linux-kmsg-format
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

```

## Platform

Ubuntu 16.04.6 LTS
Linux 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by MrAnno**
This pull request fixes the TLS connection closure on the source (receiver) side by sending back close_notify alerts.

RFC5425:
>  Once the transport receiver gets close_notify from the transport sender, it MUST reply with a close_notify unless it becomes aware that the connection has already been closed by the transport sender (e.g., the closure was indicated by TCP).

TODO:
- The destination (sender) side has to be fixed as well (in a separate PR):

> A transport sender MUST close the associated TLS connection if the connection is not expected to deliver any syslog messages later.  It MUST send a TLS close_notify alert before closing the connection.  A transport sender (TLS client) MAY choose to not wait for the transport receiver's close_notify alert and simply close the connection, thus generating an incomplete close on the transport receiver (TLS server) side.

Implementing this on the destination side is more complicated, we might need to introduce `log_proto_client_shutdown() -> log_transport_shutdown()` because `SSL_shutdown()` requires non-blocking write operations, so fd watches should be registered during shutdown. Currently, we destroy/shutdown transports after stopping watches and deiniting `LogWriter`. Another tricky part is `log_writer_reopen_deferred()`.

Fixes #2703

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng retest this please
@kira-syslogng do perftest

**Comment by MrAnno** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build SUCCESS

**Comment by furiel** [comment]
Could you please resolve the conflict?

If the source side is working, although the PR itself is incomplete, I think it would be nice to merge at least that part. The issue was raised for the source side.

We can still open a new issue for the destination though.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build FAILURE

**Comment by MrAnno** [comment]
@furiel Good idea.

I'll remove the WIP flag after running some internal tests.

**Comment by MrAnno** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/transport/transport-tls.c [hunk 1]
```diff
@@ -34,15 +34,64 @@ typedef struct _LogTransportTLS
...
+      break;
+    case SSL_ERROR_SYSCALL:
+      /* errno is set accordingly */
+      break;
+    default:
+      msg_error("SSL error while shutting down stream",
+                tls_context_format_tls_error_tag(self->tls_session->ctx),
+                tls_context_format_location_tag(self->tls_session->ctx));
+      ERR_clear_error();
+      errno = ECONNRESET;
```
Comment (furiel) [inline lib/transport/transport-tls.c:78]: > Note that SSL_shutdown() must not be called if a previous fatal error has occurred on a connection i.e. if SSL_get_error() has returned SSL_ERROR_SYSCALL or SSL_ERROR_SSL.

https://www.openssl.org/docs/man1.1.1/man3/SSL_shutdown.html

To me, this means we should not try shutdown anymore, so `self->sending_shutdown` needs to be set to `FALSE` here and the syscall branch.

Comment (MrAnno) [reply lib/transport/transport-tls.c:79]: Fatal errors are propagated back to the LogProto layer, where the connection will be closed in such cases.

But you are right, the best would be to set everything to a valid final state. Fixed.

Comment (furiel) [reply lib/transport/transport-tls.c:79]: Thanks!

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/transport/transport-tls.c [hunk 2]
```diff
@@ -31,20 +32,71 @@
...
+
 static gssize
 log_transport_tls_read_method(LogTransport *s, gpointer buf, gsize buflen, LogTransportAuxData *aux)
 {
   LogTransportTLS *self = (LogTransportTLS *) s;
   gint ssl_error;
   gint rc;
 
+  if (G_UNLIKELY(self->sending_shutdown))
+    return log_transport_tls_send_shutdown(self) >= 0 ? 0 : -1;
```
[the remark this answers is not in the document]
Comment (MrAnno) [reply lib/transport/transport-tls.c:95]: Thank you, fixed.

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/transport/transport-tls.c [hunk 3]
```diff
@@ -34,15 +34,66 @@ typedef struct _LogTransportTLS
...
+
+  if (_is_shutdown_sent(shutdown_rc))
+    {
+      self->sending_shutdown = FALSE;
+      return shutdown_rc;
+    }
+
+  gint ssl_error = SSL_get_error(self->tls_session->ssl, shutdown_rc);
+
+  switch (ssl_error)
```
Comment (lbudai) [inline lib/transport/transport-tls.c:60]: I'd factor out this part of the function (as this part does not modify the return value, it would be more readable).

Comment (MrAnno) [reply lib/transport/transport-tls.c:49]: Extracted, thanks.
The method name might not be the best.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@MrAnno :  thanks.
I'm merging this, as the last change is just a cosmetic one.
