### PR TITLE
compat/getent: fix compile error on solaris

### LINKED ISSUE #2631: make error with 3.20.1 on solaris 11.3
# syslog-ng

Hi
I am getting an error when running gmake.

error: conflicting types for (compat_generic__getprotobynumber_r)
error: conflicting types for (compat_generic__getprotobyname_r)
error: conflicting types for (compat_generic__getservbyport_r)
error: conflicting types for (compat_generic__getservbynamer_r)

modules/getent/module_getent_libtfgetent_la-tfgetent.lo error 1

/Y

### PR DESCRIPTION
**Pull request by alltilla**
The actual functions look like this:

```
#define getprotobynumber_r _compat_sun__getprotobynumber_r

/* From getent-sun.h */
/* From netdb.h (Solaris type) */

struct protoent *getprotobyname_r(const char *name,
                                  struct protoent *result, char *buffer,
                                  int buflen);

/* End from netdb.h */

int _compat_sun__getprotobynumber_r(int proto,
                                    struct protoent *result_buf, char *buf,
                                    size_t buflen, struct protoent **result);

/* End from getent-sun.h */
```

The signature are different in the 2 functions, and that is what we are fixing in the `compat` layer. We would like to use the `_compat_sun__getprotobynumber_r()` signature for `getprotobynumber_r()`.
`_compat_sun__getprotobynumber_r()` itself is just a wrapper:

```
int
_compat_sun__getprotobynumber_r(int proto,
                                struct protoent *result_buf, char *buf,
                                size_t buflen, struct protoent **result)
{
  *result = getprotobynumber_r(proto, result_buf, buf, buflen);
  return (*result ? NULL : errno);
}
```

We should not write `#define getprotobynumber_r _compat_sun__getprotobynumber_r` before declaring these functions, because it is intended to change the `getprotobyname_r()` at the call site, and not the declaration site.

Fixes #2631

Signed-off-by: Attila Szakacs <attila.szakacs@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
In the description, please add something like: getent: fix compile error on solaris

File: lib/compat/getent.h [hunk 1]
```diff
@@ -28,21 +28,21 @@
...
 #define getprotobynumber_r _compat_generic__getprotobynumber_r
 #define getprotobyname_r _compat_generic__getprotobyname_r
 #define getservbyport_r _compat_generic__getservbyport_r
 #define getservbyname_r _compat_generic__getservbyname_r
 
-#include "getent-generic.h"
-
 #elif defined(sun) || defined(__sun)
 
+#include "getent-sun.h"
```
Comment (furiel) [inline lib/compat/getent.h]: Can you explain the root cause and why the reordering fixes the problem?
Please update the commit message accordingly.

Comment (alltilla) [reply lib/compat/getent.h]: Thanks for the tip, done :)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
We were thinking a little bit more on the root cause, and it turns out it is somewhat tricky, so let me elaborate.

The problem is inside getent.h, we override `getprotobynumber_r` to another string with a define. Then we include getent-sun.h, that in terms, include solaris specific getent-related headers, that ship with their own `getprotobynumber_r` declaration, that differ from what we want to use in compat. If they were the same, we would not need to have compat at all. What is happening, is essentially our define edits everything, including solaris headers unintentionally, and hence the error.

Let me show an example on a smaller scale.

```C
$ cat foo.h 
void bar();
$ cat main.c
#define bar foo
#include "foo.h"
int foo() {}
int main(){}
$ 
```

During compile, this will be put into a single file, after expanding the include we will this:
```C
#define bar foo
void bar();
int foo() {}
int main(){}
```

After collapsing the define, we have:
```C
#define bar foo
void foo();
int foo() {}
int main(){}
```

The `void foo();` and `int foo();` declarations conflict.

**Comment by alltilla** [comment]
The actual functions look like this:

```
#define getprotobynumber_r _compat_sun__getprotobynumber_r

/* From getent-sun.h */
/* From netdb.h (Solaris type) */

struct protoent *getprotobyname_r(const char *name,
                                  struct protoent *result, char *buffer,
                                  int buflen);

/* End from netdb.h */

int _compat_sun__getprotobynumber_r(int proto,
                                    struct protoent *result_buf, char *buf,
                                    size_t buflen, struct protoent **result);

/* End from getent-sun.h */
```

The signature are different in the 2 functions, and that is what we are fixing in the `compat` layer. We would like to use the `_compat_sun__getprotobynumber_r()` signature for `getprotobynumber_r()`.
`_compat_sun__getprotobynumber_r()` itself is just a wrapper:

```
int
_compat_sun__getprotobynumber_r(int proto,
                                struct protoent *result_buf, char *buf,
                                size_t buflen, struct protoent **result)
{
  *result = getprotobynumber_r(proto, result_buf, buf, buflen);
  return (*result ? NULL : errno);
}
```

We should not write `#define getprotobynumber_r _compat_sun__getprotobynumber_r` before declaring these functions, because it is intended to change the `getprotobyname_r()` at the call site, and not the declaration site.

**Comment by alltilla** [comment]
@furiel: Updated the commit message! Thanks again :)

**Comment by kira-syslogng** [comment]
Build SUCCESS
