### PR TITLE
disk-buffer: fix "memory leak" and inconsistent buffer handling 

### LINKED ISSUE #2474: Weird value sometimes for queued stats
# syslog-ng

## Version of syslog-ng

Edit: Still occurs with syslog-ng 3 (3.25.1).

```
syslog-ng 3 (3.19.1)
Config version: 3.19
Installer-Version: 3.19.1
Revision: 3.19.1-1
Compile-Date: Dec 13 2018 15:13:38
Module-Directory: /usr/lib/syslog-ng/3.19
Module-Path: /usr/lib/syslog-ng/3.19
Include-Path: /usr/share/syslog-ng/include
Available-Modules: disk-buffer,sdjournal,tags-parser,hook-commands,dbparser,json-plugin,date,afsocket,cef,xml,kvformat,syslogformat,basicfuncs,afuser,linux-kmsg-format,system-source,cryptofuncs,csvparser,affile,pseudofile,confgen,afprog,appmodel
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

## Platform

Edit: Still occurs with Ubuntu 20.04

`Ubuntu 16.04.5` and `Ubuntu 14.04.5`

# Issue

## Failure

We have a monitoring that check every 30s the value of the stats: processed, written, dropped and queued.

It often happened that a weird value is retrieve for the stats `queued` only. Here are some example of values:
- 623114166329008768.000000
- 616167067881942784.000000
- 602754809439916928.000000
- 617238611323253888.000000

That's always this same format.

## Steps to reproduce

The command used to retrieve the info is: `/usr/sbin/syslog-ng-ctl query get "*d_logstash*queued" | cut -d "=" -f2`

## Configuration

```
@version: 3.19
@include "scl.conf"

# Syslog-ng configuration file, compatible with default Debian syslogd
# installation.

# First, set some global options.
options { chain_hostnames(off); flush_lines(0); use_dns(no); use_fqdn(no);
	  owner("root"); group("adm"); perm(0640); stats_freq(0);
	  bad_hostname("^gconfd$");
};

########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src {
       system();
       internal();
};

# If you wish to get logs from remote machine you should uncomment
# this and comment the above source line.
#
#source s_net { tcp(ip(127.0.0.1) port(1000)); };

########################
# Destinations
########################
# First some standard logfile
#
destination d_auth { file("/var/log/auth.log"); };
destination d_cron { file("/var/log/cron.log"); };
destination d_daemon { file("/var/log/daemon.log"); };
destination d_kern { file("/var/log/kern.log"); };
destination d_lpr { file("/var/log/lpr.log"); };
destination d_mail { file("/var/log/mail.log"); };
destination d_syslog { file("/var/log/syslog"); };
destination d_user { file("/var/log/user.log"); };
destination d_uucp { file("/var/log/uucp.log"); };

# This files are the log come from the mail subsystem.
#
destination d_mailinfo { file("/var/log/mail.info"); };
destination d_mailwarn { file("/var/log/mail.warn"); };
destination d_mailerr { file("/var/log/mail.err"); };

# Logging for INN news system
#
destination d_newscrit { file("/var/log/news/news.crit"); };
destination d_newserr { file("/var/log/news/news.err"); };
destination d_newsnotice { file("/var/log/news/news.notice"); };

# Some 'catch-all' logfiles.
#
destination d_debug { file("/var/log/debug"); };
destination d_error { file("/var/log/error"); };
destination d_messages { file("/var/log/messages"); };

# The root's console.
#
destination d_console { usertty("root"); };

# Virtual console.
#
destination d_console_all { file(`tty10`); };

# The named pipe /dev/xconsole is for the nsole' utility.  To use it,
# you must invoke nsole' with the -file' option:
#
#    $ xconsole -file /dev/xconsole [...]
#
destination d_xconsole { pipe("/dev/xconsole"); };

# Send the messages to an other host
#
#destination d_net { tcp("127.0.0.1" port(1000) log_fifo_size(1000)); };

# Debian only
destination d_ppp { file("/var/log/ppp.log"); };

########################
# Filters
########################
# Here's come the filter options. With this rules, we can set which 
# message go where.

filter f_dbg { level(debug); };
filter f_info { level(info); };
filter f_notice { level(notice); };
filter f_warn { level(warn); };
filter f_err { level(err); };
filter f_crit { level(crit .. emerg); };

filter f_debug { level(debug) and not facility(auth, authpriv, news, mail); };
filter f_error { level(err .. emerg) ; };
filter f_messages { level(info,notice,warn) and 
                    not facility(auth,authpriv,cron,daemon,mail,news); };

filter f_auth { facility(auth, authpriv) and not filter(f_debug); };
filter f_cron { facility(cron) and not filter(f_debug); };
filter f_daemon { facility(daemon) and not filter(f_debug); };
filter f_kern { facility(kern) and not filter(f_debug); };
filter f_lpr { facility(lpr) and not filter(f_debug); };
filter f_local { facility(local0, local1, local3, local4, local5,
                        local6, local7) and not filter(f_debug); };
filter f_mail { facility(mail) and not filter(f_debug); };
filter f_news { facility(news) and not filter(f_debug); };
filter f_syslog3 { not facility(auth, authpriv, mail) and not filter(f_debug); };
filter f_user { facility(user) and not filter(f_debug); };
filter f_uucp { facility(uucp) and not filter(f_debug); };

filter f_cnews { level(notice, err, crit) and facility(news); };
filter f_cother { level(debug, info, notice, warn) or facility(daemon, mail); };

filter f_ppp { facility(local2) and not filter(f_debug); };
filter f_console { level(warn .. emerg); };

########################
# Log paths
########################
log { source(s_src); filter(f_auth); destination(d_auth); };
log { source(s_src); filter(f_cron); destination(d_cron); };
log { source(s_src); filter(f_daemon); destination(d_daemon); };
log { source(s_src); filter(f_kern); destination(d_kern); };
log { source(s_src); filter(f_lpr); destination(d_lpr); };
log { source(s_src); filter(f_syslog3); destination(d_syslog); };
log { source(s_src); filter(f_user); destination(d_user); };
log { source(s_src); filter(f_uucp); destination(d_uucp); };

log { source(s_src); filter(f_mail); destination(d_mail); };
#log { source(s_src); filter(f_mail); filter(f_info); destination(d_mailinfo); };
#log { source(s_src); filter(f_mail); filter(f_warn); destination(d_mailwarn); };
#log { source(s_src); filter(f_mail); filter(f_err); destination(d_mailerr); };

log { source(s_src); filter(f_news); filter(f_crit); destination(d_newscrit); };
log { source(s_src); filter(f_news); filter(f_err); destination(d_newserr); };
log { source(s_src); filter(f_news); filter(f_notice); destination(d_newsnotice); };
#log { source(s_src); filter(f_cnews); destination(d_console_all); };
#log { source(s_src); filter(f_cother); destination(d_console_all); };

#log { source(s_src); filter(f_ppp); destination(d_ppp); };

log { source(s_src); filter(f_debug); destination(d_debug); };
log { source(s_src); filter(f_error); destination(d_error); };
log { source(s_src); filter(f_messages); destination(d_messages); };

log { source(s_src); filter(f_console); destination(d_console_all);
				    destination(d_xconsole); };
log { source(s_src); filter(f_crit); destination(d_console); };

# All messages send to a remote site
#
#log { source(s_src); destination(d_net); };

###
# Include all config files in /etc/syslog-ng/conf.d/
###
@include "/etc/syslog-ng/conf.d/*.conf"

```

### PR DESCRIPTION
**Pull request by MrAnno**
The reliable disk buffer maintains in-memory copies of the "beginning" and the "end" of the disk buffer for performance and flow-control purposes.

These memory buffers are not necessarily continuous slices of the disk buffer file, so they are emptied by a logic that queries the reader head of QDisk.

Currently, it is not allowed for the reader and writer heads to overlap when the buffer is full, so it is possible that the read head points to the very end of the file, but the next read will be done from the beginning of the file.

This corner case has to be taken into account when comparing the current position with in-memory copies.

Note: In the next PR, I'll try to get rid of all the reader/writer/backlog head correction trickeries. It would greatly reduce the complexity of QDisk.

Fixes #2474 (as well)

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by MrAnno** [comment]
@Barkodcz Thanks for reproducing this. I believe everything has been fixed now.

I've had enough of these corner-case bugs, so I decided to run a fuzzer on QDisk after opening my position-simplification pull request.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@MrAnno do stresstest

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

File: modules/diskq/qdisk.c [hunk 1]
```diff
@@ -561,38 +560,106 @@ qdisk_pop_head(QDisk *self, GString *record)
...
+      _maybe_apply_non_reliable_corrections(self);
+    }
+
+  return success;
+}
+
+gboolean
+qdisk_ack_backlog(QDisk *self)
+{
+  if (self->hdr->backlog_len <= 0)
```
Comment (OverOrion) [inline modules/diskq/qdisk.c:617]: Is it possible for backlog_len to be negative? If not, how about changing "<=" to "=="?

File: modules/diskq/logqueue-disk-reliable.c [hunk 2]
```diff
@@ -367,8 +367,12 @@ _push_tail(LogQueue *s, LogMessage *msg, const LogPathOptions *path_options)
   log_msg_unref(msg);
 
 exit:
-  log_queue_push_notify(s);
   log_queue_queued_messages_inc(s);
+
+  /* this releases the queue's lock for a short time, which may violate the
+   * consistency of the disk-buffer, so it must be the last call under lock in this function
+   */
+  log_queue_push_notify(s);
```
Comment (OverOrion) [inline modules/diskq/logqueue-disk-reliable.c:375]: This is the reason the momentarily underflow has been fixed.

**Review by alltilla — APPROVED** [review]
Amazing refactor and fix! `QDisk` is shaping nicely :)

File: modules/diskq/qdisk.c [hunk 3]
```diff
@@ -519,39 +519,38 @@ _read_record_from_disk(QDisk *self, GString *record, guint32 record_length)
...
-  gint64 new_read_head_position = self->hdr->read_head + record_length + sizeof(record_length);
-
-  if (new_read_head_position > self->hdr->write_head)
-    new_read_head_position = _correct_position_if_max_size_is_reached(self, &new_read_head_position);
+  if (self->options->reliable)
+    return;
 
-  return new_read_head_position;
+  qdisk_empty_backlog(self);
+  g_assert(self->hdr->backlog_len == 0);
```
Comment (Barkodcz) [inline modules/diskq/qdisk.c:529]: Optional: I think, the assert is unnecessary here. 
From the commit history, I get why is here, but for the end "production" I don't think is needed here.

File: modules/diskq/qdisk.c [hunk 4]
```diff
@@ -519,39 +519,38 @@ _read_record_from_disk(QDisk *self, GString *record, guint32 record_length)
...
-        {
-          qdisk_reset_file_if_empty(self);
-        }
-    }
+  *position = new_read_head_position;
 }
 
 gint64
-qdisk_get_head_position(QDisk *self)
+qdisk_get_next_head_position(QDisk *self)
```
Comment (Barkodcz) [inline modules/diskq/qdisk.c:547]: Optional: 
for me, I don't get it it will return the value of the next read head, I think it would be better to name the `qdisk_get_next_read_head_position`

File: modules/diskq/logqueue-disk-reliable.c [hunk 5]
```diff
@@ -332,13 +315,22 @@ _push_tail(LogQueue *s, LogMessage *msg, const LogPathOptions *path_options)
   gint64 message_position = qdisk_get_next_tail_position(self->super.qdisk);
   if (!qdisk_push_tail(self->super.qdisk, serialized_msg))
     {
+      EVTTAG *suggestion = NULL;
+      if (path_options->flow_control_requested)
+        {
+          suggestion = evt_tag_str("suggestion", "consider increasing mem-buf-size() or decreasing log-iw-size() "
+                                   "values on the source side to avoid message loss");
```
Comment (Barkodcz) [inline modules/diskq/logqueue-disk-reliable.c:322]: I think it's very cool to make these suggestions! Is possible to make more suggestions elsewhere?

**Review by Barkodcz — COMMENTED** [review]
Very nice PR, big thumbs up!

I tried to reproduce the original problem, but I can't. So I think the problem was fixed!

File: modules/diskq/qdisk.c (hunk 3 above)
Comment (MrAnno) [reply modules/diskq/qdisk.c:529]: This was already here, I just did not notice this should be removed.
It has become a tautology.

Thanks, I'll remove it.

File: modules/diskq/qdisk.c (hunk 4 above)
Comment (MrAnno) [reply modules/diskq/qdisk.c:547]: This naming convention already exists in the QDisk interface, if you check its header file.
Considering QDisk as a ring-buffer on disk, or a LogQueue implementation, "reader" and "writer"  are redundant terms.

Queues usually have a head or tail, which can internally mean they have a reader or writer pointers.
Attila decided not to publish these names, I like the idea.

Note: The getters at the bottom of the QDisk headers are not meant to be public, they are only there so we can do nasty things in unit tests (which we should not do), but those are not part of the real interface.

File: modules/diskq/logqueue-disk-reliable.c (hunk 5 above)
Comment (MrAnno) [reply modules/diskq/logqueue-disk-reliable.c:322]: AFAIK this is the only remaining part where we can lose messages by a log-fifo-size() misconfiguration.
For example, we don't drop flow-controlled messages anymore in LogQueueFifo.

File: modules/diskq/qdisk.c (hunk 4 above)
Comment (Barkodcz) [reply modules/diskq/qdisk.c:547]: ohh okay, thanks!

File: modules/diskq/qdisk.c [hunk 6]
```diff
@@ -439,9 +439,9 @@ qdisk_push_tail(QDisk *self, GString *record)
 }
 
 static inline gssize
-_read_record_length_from_disk(QDisk *self, guint32 *record_length)
+_read_record_length_from_disk(QDisk *self, gint64 position, guint32 *record_length)
```
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/qdisk.c:442]: I did this by accident, thank you for noticing. Fixed.

File: modules/diskq/qdisk.c [hunk 7]
```diff
@@ -533,14 +533,14 @@ _maybe_apply_non_reliable_corrections(QDisk *self)
 
 
 static inline void
-_update_positions_after_read(QDisk *self, guint32 record_length)
+_update_positions_after_read(QDisk *self, guint32 record_length, gint64 *position)
 {
-  gint64 new_read_head_position = self->hdr->read_head + record_length + sizeof(record_length);
+  gint64 new_read_head_position = *position + record_length + sizeof(record_length);
```
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/qdisk.c:538]: Done.

File: modules/diskq/qdisk.c [hunk 8]
```diff
@@ -589,22 +589,22 @@ qdisk_read(QDisk *self, gpointer buffer, gsize bytes_to_read, gint64 position)
   return res;
 }
 
-gint64
-qdisk_skip_record(QDisk *self, gint64 position)
+gboolean
+qdisk_skip_record(QDisk *self, gint64 position, gint64 *new_position)
```
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/qdisk.c:581]: I'd skip this for now.

File: modules/diskq/qdisk.c [hunk 9]
```diff
@@ -572,7 +572,7 @@ qdisk_pop_head(QDisk *self, GString *record)
   return TRUE;
 }
 
-gboolean
+static gboolean
```
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/qdisk.c:580]: Done.

File: modules/diskq/qdisk.c (hunk 1 above)
Comment (MrAnno) [reply modules/diskq/qdisk.c:617]: Done, thanks.

**Comment by MrAnno** [comment]
I think I've addressed all review notes (except for one optional).

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — DISMISSED** [review]

**Comment by MrAnno** [comment]
I've resolved a conflict.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by alltilla — APPROVED** [review]

**Review by OverOrion — APPROVED** [review]
