### PR TITLE
kafka-c: Fix multiple memleaks

### LINKED ISSUE #2929: Possible memory leak (or misconfiguration)
# syslog-ng

## Version of syslog-ng

```
[root@pleistocene11 ~]# /logs/lvapp/sbin/syslog-ng --version
syslog-ng 3 (3.23.1)
Config version: 3.23
Installer-Version: 3.23.1
Revision:
Compile-Date: Sep 11 2019 17:44:21
Module-Directory: /logs/lvapp/lib/syslog-ng
Module-Path: /logs/lvapp/lib/syslog-ng
Include-Path: /logs/lvapp/share/syslog-ng/include
Available-Modules: map-value-pairs,cryptofuncs,afsocket,snmptrapd-parser,http,dbparser,linux-kmsg-format,kvformat,syslogformat,confgen,disk-buffer,json-plugin,cef,stardate,hook-commands,graphite,examples,basicfuncs,xml,system-source,date,afprog,afuser,pseudofile,tags-parser,affile,appmodel,tfgetent,afstomp,csvparser,kafka,add-contextual-data
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: off
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

```

## Platform

rhel6.10

# Issue

## Failure
Hi,
I switched from v3.9 to v3.23.
The daemon is handling a large amont of UDP logs (~10KEPS ) from many sources.
Everything is written to :
1/ A single big file
2/ One file per equipment sending logs
3/ Kafkac output

The config file is quite complex and it is hard to reproduce the issue in lab without the real trafic making this hard to debug. As it is in prod, it is also very hard to do try and error with the config.

I used pmap -x on 2 occasion to track the change in the allocated memory, between the run there were several new 131072KB annon pages allocated. I dumped one of those pages with gdb, it contains lots of log data from different equipments, however I have no idea how to track with part or the code or which component did this allocation.

Ram usage is after 1 day at 29GB.

```
Address	Kbytes	Is in previous pmap	RSS	Dirty	Mode	Mapping		
total	kB		29939612	18249092	18246044			
----------------	------		------	------				
00007f7de0000000	133228	00007f7de0000000	508	508	rw---	[	anon	]
00007f7818000000	131072	#N/A	131072	131072	rw---	[	anon	]
00007f7820000000	131072	#N/A	131072	131072	rw---	[	anon	]
00007f7828000000	131072	#N/A	131072	131072	rw---	[	anon	]
00007f7830000000	131072	#N/A	131072	131072	rw---	[	anon	]
00007f7840000000	131072	#N/A	131072	131072	rw---	[	anon	]
00007f7848000000	131072	#N/A	131072	131072	rw---	[	anon	]
00007f7860000000	131072	#N/A	131072	131072	rw---	[	anon	]
00007f7870000000	131072	00007f7870000000	131072	131072	rw---	[	anon	]
00007f7878000000	131072	00007f7878000000	131072	131072	rw---	[	anon	]
00007f7880000000	131072	00007f7880000000	131072	131072	rw---	[	anon	]
00007f7888000000	131072	00007f7888000000	131072	131072	rw---	[	anon	]
00007f7890000000	131072	00007f7890000000	131072	131072	rw---	[	anon	]
00007f78a8000000	131072	00007f78a8000000	131072	131072	rw---	[	anon	]
00007f78b0000000	131072	00007f78b0000000	131072	131072	rw---	[	anon	]
00007f78b8000000	131072	00007f78b8000000	131072	131072	rw---	[	anon	]
00007f78c0000000	131072	00007f78c0000000	131072	131072	rw---	[	anon	]
00007f78c8000000	131072	00007f78c8000000	131072	131072	rw---	[	anon	]
00007f78e0000000	131072	00007f78e0000000	131072	131072	rw---	[	anon	]
00007f78e8000000	131072	00007f78e8000000	131072	131072	rw---	[	anon	]
00007f78f0000000	131072	00007f78f0000000	131072	131072	rw---	[	anon	]
00007f78f8000000	131072	00007f78f8000000	131072	131072	rw---	[	anon	]
00007f7900000000	131072	00007f7900000000	131072	131072	rw---	[	anon	]
00007f7908000000	131072	00007f7908000000	131072	131072	rw---	[	anon	]
00007f7910000000	131072	00007f7910000000	131072	131072	rw---	[	anon	]
00007f7918000000	131072	00007f7918000000	131072	131072	rw---	[	anon	]
00007f7920000000	131072	00007f7920000000	131072	131072	rw---	[	anon	]
00007f7940000000	131072	00007f7940000000	131072	131072	rw---	[	anon	]
00007f7948000000	131072	00007f7948000000	131072	131072	rw---	[	anon	]
00007f7968000000	131072	00007f7968000000	131072	131072	rw---	[	anon	]
00007f7978000000	131072	00007f7978000000	131072	131072	rw---	[	anon	]
00007f7980000000	131072	00007f7980000000	131072	131072	rw---	[	anon	]
00007f7990000000	131072	00007f7990000000	131072	131072	rw---	[	anon	]
00007f79d0000000	131072	00007f79d0000000	131072	131072	rw---	[	anon	]
00007f79e0000000	131072	00007f79e0000000	131072	131072	rw---	[	anon	]
00007f7a20000000	131072	00007f7a20000000	131072	131072	rw---	[	anon	]
00007f7a58000000	131072	00007f7a58000000	131072	131072	rw---	[	anon	]
00007f7a60000000	131072	00007f7a60000000	131072	131072	rw---	[	anon	]
00007f7a68000000	131072	00007f7a68000000	131072	131072	rw---	[	anon	]
00007f7aa0000000	131072	00007f7aa0000000	131072	131072	rw---	[	anon	]
00007f7ab0000000	131072	00007f7ab0000000	131072	131072	rw---	[	anon	]
00007f7ac0000000	131072	00007f7ac0000000	131072	131072	rw---	[	anon	]
00007f7ae0000000	131072	00007f7ae0000000	131072	131072	rw---	[	anon	]
00007f7b38000000	131072	00007f7b38000000	131072	131072	rw---	[	anon	]
00007f7b78000000	131072	00007f7b78000000	127976	127976	rw---	[	anon	]
00007f7b90000000	131072	00007f7b90000000	130700	130700	rw---	[	anon	]
00007f7bb8000000	131072	00007f7bb8000000	129116	129116	rw---	[	anon	]
00007f7bc8000000	131072	00007f7bc8000000	112344	112344	rw---	[	anon	]
00007f7bd0000000	131072	00007f7bd0000000	6752	6752	rw---	[	anon	]
00007f7bf0000000	131072	00007f7bf0000000	4384	4384	rw---	[	anon	]
00007f7c40000000	131072	00007f7c40000000	3460	3460	rw---	[	anon	]
00007f7c48000000	131072	00007f7c48000000	7316	7316	rw---	[	anon	]
00007f7c60000000	131072	00007f7c60000000	4916	4916	rw---	[	anon	]
00007f7c70000000	131072	00007f7c70000000	1860	1860	rw---	[	anon	]
00007f7c98000000	131072	00007f7c98000000	8368	8368	rw---	[	anon	]
00007f7cc0000000	131072	00007f7cc0000000	6224	6224	rw---	[	anon	]
00007f7cc8000000	131072	00007f7cc8000000	5612	5612	rw---	[	anon	]
00007f7cd8000000	131072	00007f7cd8000000	43572	43572	rw---	[	anon	]
00007f7cf0000000	131072	00007f7cf0000000	35156	35156	rw---	[	anon	]
00007f7d08000000	131072	00007f7d08000000	131072	131072	rw---	[	anon	]
00007f7d28000000	131072	00007f7d28000000	48372	48372	rw---	[	anon	]
00007f7d30000000	131072	00007f7d30000000	93384	93384	rw---	[	anon	]
00007f7d38000000	131072	00007f7d38000000	19116	19116	rw---	[	anon	]
00007f7d40000000	131072	00007f7d40000000	97316	97316	rw---	[	anon	]
00007f7d50000000	131072	00007f7d50000000	53992	53992	rw---	[	anon	]
00007f7d70000000	131072	00007f7d70000000	129040	129040	rw---	[	anon	]
00007f7d78000000	131072	00007f7d78000000	120836	120836	rw---	[	anon	]
00007f7d80000000	131072	00007f7d80000000	71272	71272	rw---	[	anon	]
00007f7d88000000	131072	00007f7d88000000	65636	65636	rw---	[	anon	]
00007f7d90000000	131072	00007f7d90000000	84932	84932	rw---	[	anon	]
00007f7da8000000	131072	00007f7da8000000	872	872	rw---	[	anon	]
00007f7dc0000000	131072	00007f7dc0000000	440	440	rw---	[	anon	]
00007f7dd0000000	131072	00007f7dd0000000	576	576	rw---	[	anon	]
00007f7df8000000	131072	00007f7df8000000	468	468	rw---	[	anon	]
00007f7e08000000	131072	00007f7e08000000	388	388	rw---	[	anon	]
00007f7e20000000	131072	00007f7e20000000	108	108	rw---	[	anon	]
00007f7e28000000	131072	00007f7e28000000	228	228	rw---	[	anon	]
00007f7e30000000	131072	00007f7e30000000	96	96	rw---	[	anon	]
00007f7e40000000	131072	00007f7e40000000	284	284	rw---	[	anon	]
00007f7e48000000	131072	00007f7e48000000	92	92	rw---	[	anon	]
00007f7e50000000	131072	00007f7e50000000	1140	1140	rw---	[	anon	]
00007f7e58000000	131072	00007f7e58000000	2308	2308	rw---	[	anon	]
00007f7e60000000	131072	00007f7e60000000	116	116	rw---	[	anon	]
00007f7e68000000	131072	00007f7e68000000	0	0	rw---	[	anon	]
00007f7e70000000	131072	00007f7e70000000	468	468	rw---	[	anon	]
00007f7e78000000	131072	00007f7e78000000	568	568	rw---	[	anon	]
00007f7e80000000	131072	00007f7e80000000	1192	1192	rw---	[	anon	]
00007f7e88000000	131072	00007f7e88000000	684	684	rw---	[	anon	]
00007f7e98000000	131072	00007f7e98000000	12	12	rw---	[	anon	]
00007f7ea0000000	131072	00007f7ea0000000	20	20	rw---	[	anon	]
00007f7ea8000000	131072	00007f7ea8000000	20	20	rw---	[	anon	]
00007f7eb0000000	131072	00007f7eb0000000	0	0	rw---	[	anon	]
00007f7eb8000000	131072	00007f7eb8000000	152	152	rw---	[	anon	]
00007f7b18000000	130564	00007f7b18000000	130564	130564	rw---	[	anon	]
00007f7d48000000	128668	00007f7d48000000	115184	115184	rw---	[	anon	]
00007f7e18418000	126880	00007f7e18418000	336	336	rw---	[	anon	]
00007f7d605eb000	125012	00007f7d605eb000	88636	88636	rw---	[	anon	]
00007f79386c4000	124144	00007f79386c4000	124144	124144	rw---	[	anon	]
00007f7bf8725000	123756	00007f7bf8725000	20160	20160	rw---	[	anon	]
00007f7b88000000	123048	00007f7b88000000	121444	121444	rw---	[	anon	]
00007f7e107d6000	123048	00007f7e107d6000	1192	1192	rw---	[	anon	]
00007f7ab8000000	122988	00007f7ab8000000	122988	122988	rw---	[	anon	]
00007f7a48000000	122364	00007f7a48000000	122364	122364	rw---	[	anon	]
00007f7bc0adb000	119956	00007f7bc0adb000	87268	87268	rw---	[	anon	]
00007f78d0d5b000	117396	00007f78d0d5b000	117396	117396	rw---	[	anon	]
00007f7af8000000	117236	00007f7af8000000	117236	117236	rw---	[	anon	]
00007f7bb0e65000	116332	00007f7bb0e65000	114804	114804	rw---	[	anon	]
00007f79a8000000	115960	00007f79a8000000	115960	115960	rw---	[	anon	]
00007f7998f43000	115444	00007f7998f43000	115444	115444	rw---	[	anon	]
00007f7a88eba000	115304	00007f7a88eba000	115304	115304	rw---	[	anon	]
00007f7b60000000	115256	00007f7b60000000	107320	107320	rw---	[	anon	]
00007f7e90000000	114788	00007f7e90000000	9608	9608	rw---	[	anon	]
00007f7c78ffe000	114696	00007f7c78ffe000	124	124	rw---	[	anon	]
00007f792913c000	113424	00007f792913c000	113424	113424	rw---	[	anon	]
00007f7ca11f6000	112680	00007f7ca11f6000	1036	1036	rw---	[	anon	]
00007f7838000000	111144	#N/A	111144	111144	rw---	[	anon	]
00007f7ce13ad000	110924	00007f7ce13ad000	8280	8280	rw---	[	anon	]
00007f79b13c4000	110832	00007f79b13c4000	110832	110832	rw---	[	anon	]
00007f7ad94d2000	109752	00007f7ad94d2000	109752	109752	rw---	[	anon	]
00007f78d94db000	109716	00007f78d94db000	109716	109716	rw---	[	anon	]
00007f7a29541000	109308	00007f7a29541000	109308	109308	rw---	[	anon	]
00007f7b99626000	108392	00007f7b99626000	108116	108116	rw---	[	anon	]
00007f7930000000	108388	00007f7930000000	108388	108388	rw---	[	anon	]
00007f7c81701000	107516	00007f7c81701000	872	872	rw---	[	anon	]
00007f7ce9786000	106984	00007f7ce9786000	5872	5872	rw---	[	anon	]
00007f7ec0000000	106816	00007f7ec0000000	176	176	rw---	[	anon	]
00007f7a317e2000	106616	00007f7a317e2000	106616	106616	rw---	[	anon	]
00007f7a818b5000	105772	00007f7a818b5000	105772	105772	rw---	[	anon	]
00007f7be172a000	105576	00007f7be172a000	8480	8480	rw---	[	anon	]
00007f7898000000	105484	00007f7898000000	105484	105484	rw---	[	anon	]
00007f7b09ab6000	103720	00007f7b09ab6000	103720	103720	rw---	[	anon	]
00007f7de821f000	102548	00007f7de821f000	23628	23628	rw---	[	anon	]
00007f7e39c78000	101920	00007f7e39c78000	1656	1656	rw---	[	anon	]
00007f79a1db7000	100644	00007f79a1db7000	100644	100644	rw---	[	anon	]
00007f7ac9e66000	99944	00007f7ac9e66000	99944	99944	rw---	[	anon	]
00007f79c1e75000	99884	00007f79c1e75000	99884	99884	rw---	[	anon	]
00007f7970000000	99188	00007f7970000000	99188	99188	rw---	[	anon	]
00007f7c0a119000	97180	00007f7c0a119000	9216	9216	rw---	[	anon	]
00007f7b5a253000	95924	00007f7b5a253000	94832	94832	rw---	[	anon	]
00007f7868000000	95664	#N/A	95664	95664	rw---	[	anon	]
00007f7d5a301000	95228	00007f7d5a301000	49540	49540	rw---	[	anon	]
00007f7d02410000	94144	00007f7d02410000	92160	92160	rw---	[	anon	]
00007f7b824ad000	93516	00007f7b824ad000	92900	92900	rw---	[	anon	]
00007f7b50000000	93500	00007f7b50000000	93500	93500	rw---	[	anon	]
00007f7cfa5a9000	92508	00007f7cfa5a9000	92160	92160	rw---	[	anon	]
00007f7ba8000000	92292	00007f7ba8000000	92292	92292	rw---	[	anon	]
00007f7aaa6df000	91268	00007f7aaa6df000	91268	91268	rw---	[	anon	]
00007f79ea709000	91100	00007f79ea709000	91100	91100	rw---	[	anon	]
00007f7a78000000	90584	00007f7a78000000	90584	90584	rw---	[	anon	]
00007f7a10000000	90248	00007f7a10000000	90248	90248	rw---	[	anon	]
00007f79f0ce0000	89948	00007f79f0ce0000	89948	89948	rw---	[	anon	]
00007f7cb28f4000	89136	00007f7cb28f4000	10200	10200	rw---	[	anon	]
00007f7c58000000	89064	00007f7c58000000	8488	8488	rw---	[	anon	]
00007f785a96d000	88652	#N/A	88652	88652	rw---	[	anon	]
00007f7c3a974000	88624	00007f7c3a974000	5564	5564	rw---	[	anon	]
00007f7c10c99000	88180	00007f7c10c99000	6604	6604	rw---	[	anon	]
00007f78a0000000	87796	00007f78a0000000	87796	87796	rw---	[	anon	]
00007f7b12ad1000	87228	00007f7b12ad1000	87228	87228	rw---	[	anon	]
00007f7a3aae6000	87144	00007f7a3aae6000	87144	87144	rw---	[	anon	]
00007f7d20000000	87108	00007f7d20000000	5260	5260	rw---	[	anon	]
00007f7d9ab98000	86432	00007f7d9ab98000	1016	1016	rw---	[	anon	]
00007f7c2ad96000	84392	00007f7c2ad96000	4420	4420	rw---	[	anon	]
00007f7ad0000000	84116	00007f7ad0000000	84116	84116	rw---	[	anon	]
00007f7c50000000	83848	00007f7c50000000	3440	3440	rw---	[	anon	]
00007f7c18000000	82648	00007f7c18000000	284	284	rw---	[	anon	]
00007f79baf63000	82548	00007f79baf63000	82548	82548	rw---	[	anon	]
00007f7c68000000	81800	00007f7c68000000	20	20	rw---	[	anon	]
00007f7808541000	81736	#N/A	81736	81736	rw---	[	anon	]
00007f7960000000	81324	00007f7960000000	81324	81324	rw---	[	anon	]
00007f7a19225000	81112	00007f7a19225000	81112	81112	rw---	[	anon	]
00007f79db108000	80864	00007f79db108000	80864	80864	rw---	[	anon	]
00007f7b4a294000	80064	00007f7b4a294000	79184	79184	rw---	[	anon	]
00007f7cb8000000	80048	00007f7cb8000000	4900	4900	rw---	[	anon	]
00007f7cd3275000	79404	00007f7cd3275000	20272	20272	rw---	[	anon	]
00007f7d132a2000	79224	00007f7d132a2000	39520	39520	rw---	[	anon	]
00007f79f8000000	75612	00007f79f8000000	75612	75612	rw---	[	anon	]
00007f7a91230000	75612	00007f7a91230000	75612	75612	rw---	[	anon	]
00007f7e00000000	75528	00007f7e00000000	48	48	rw---	[	anon	]
00007f7c219d9000	75060	00007f7c219d9000	1628	1628	rw---	[	anon	]
00007f7c88000000	74832	00007f7c88000000	1708	1708	rw---	[	anon	]
00007f7958000000	73136	00007f7958000000	73136	73136	rw---	[	anon	]
00007f7c00000000	73100	00007f7c00000000	7152	7152	rw---	[	anon	]
00007f7950000000	72884	00007f7950000000	72884	72884	rw---	[	anon	]
00007f7dbb973000	72244	00007f7dbb973000	648	648	rw---	[	anon	]
00007f7af2652000	71612	00007f7af2652000	71612	71612	rw---	[	anon	]
00007f7bd8000000	71364	00007f7bd8000000	2356	2356	rw---	[	anon	]
00007f7d1b96f000	71192	00007f7d1b96f000	18632	18632	rw---	[	anon	]
00007f7db3af7000	70692	00007f7db3af7000	224	224	rw---	[	anon	]
00007f7d6bb07000	70628	00007f7d6bb07000	31408	31408	rw---	[	anon	]
00007f7813b67000	70244	#N/A	70244	70244	rw---	[	anon	]
00007f7a9bbc7000	69860	00007f7a9bbc7000	69860	69860	rw---	[	anon	]
00007f7da3677000	68536	00007f7da3677000	61452	61452	rw---	[	anon	]
00007f7b00000000	67952	00007f7b00000000	67952	67952	rw---	[	anon	]
00007f7ba0aad000	67084	00007f7ba0aad000	65676	65676	rw---	[	anon	]
00007f798bf96000	65960	00007f798bf96000	65960	65960	rw---	[	anon	]
00007f7c92f8c000	65800	00007f7c92f8c000	152	152	rw---	[	anon	]
00007f7dcc000000	65536	00007f7dcc000000	800	800	rw---	[	anon	]
00007f7df0000000	65536	00007f7df0000000	36	36	rw---	[	anon	]
00007f7ed8000000	65536	00007f7ed8000000	92	92	rw---	[	anon	]
00007f7f0c000000	65536	00007f7f0c000000	2092	2092	rw---	[	anon	]
00007f7f14023000	65396	00007f7f14023000	0	0	-----	[	anon	]
00007f7f18023000	65396	00007f7f18023000	0	0	-----	[	anon	]
00007f7f20023000	65396	00007f7f20023000	0	0	-----	[	anon	]
00007f7f24023000	65396	00007f7f24023000	0	0	-----	[	anon	]
00007f7f28023000	65396	00007f7f28023000	0	0	-----	[	anon	]
00007f7ec8021000	65160	00007f7ec8021000	0	0	-----	[	anon	]
00007f7988000000	65092	00007f7988000000	65092	65092	rw---	[	anon	]
00007f7a4046a000	64204	00007f7a4046a000	64204	64204	rw---	[	anon	]
00007f7a7415a000	64152	00007f7a7415a000	64152	64152	rw---	[	anon	]
00007f7a08000000	64004	00007f7a08000000	64004	64004	rw---	[	anon	]
00007f7ae8000000	63928	00007f7ae8000000	63928	63928	rw---	[	anon	]
00007f7ed0083000	63908	00007f7ed0083000	0	0	-----	[	anon	]
00007f7cac1ab000	63828	00007f7cac1ab000	3140	3140	rw---	[	anon	]
00007f7ef4308000	62432	00007f7ef4308000	0	0	-----	[	anon	]
00007f7ef8308000	62432	00007f7ef8308000	0	0	-----	[	anon	]
00007f7efc308000	62432	00007f7efc308000	0	0	-----	[	anon	]
00007f7a50000000	62392	00007f7a50000000	62392	62392	rw---	[	anon	]
00007f7a44356000	62120	00007f7a44356000	62120	62120	rw---	[	anon	]
00007f7810000000	60580	#N/A	60580	60580	rw---	[	anon	]
00007f7d68000000	60440	00007f7d68000000	59392	59392	rw---	[	anon	]
00007f7db0000000	60216	00007f7db0000000	64	64	rw---	[	anon	]
00007f7b20000000	59460	00007f7b20000000	59460	59460	rw---	[	anon	]
00007f7db8000000	58796	00007f7db8000000	180	180	rw---	[	anon	]
00007f7ed4021000	58688	00007f7ed4021000	0	0	-----	[	anon	]
00007f7aec70d000	58316	00007f7aec70d000	58316	58316	rw---	[	anon	]
00007f7c0477d000	57868	00007f7c0477d000	9220	9220	rw---	[	anon	]
00007f7850000000	55760	#N/A	55760	55760	rw---	[	anon	]
00007f7da0000000	55500	00007f7da0000000	26988	26988	rw---	[	anon	]
00007f79fc9de000	55432	00007f79fc9de000	55432	55432	rw---	[	anon	]
00007f7e049ec000	55376	00007f7e049ec000	0	0	rw---	[	anon	]
00007f7b30000000	54332	00007f7b30000000	54332	54332	rw---	[	anon	]
00007f7edc5a8000	52800	00007f7edc5a8000	0	0	-----	[	anon	]
00007f7b2cd51000	51900	00007f7b2cd51000	51900	51900	rw---	[	anon	]
00007f7cd0000000	51076	00007f7cd0000000	1360	1360	rw---	[	anon	]
00007f7c31e73000	50920	00007f7c31e73000	2376	2376	rw---	[	anon	]
00007f7b6aa37000	50804	00007f7b6aa37000	49256	49256	rw---	[	anon	]
00007f79c8000000	49984	00007f79c8000000	49984	49984	rw---	[	anon	]
00007f79d8000000	49940	00007f79d8000000	49940	49940	rw---	[	anon	]
00007f7a02080000	49636	00007f7a02080000	49636	49636	rw---	[	anon	]
00007f7d1023b000	49344	00007f7d1023b000	47108	47108	rw---	[	anon	]
00007f7a5504f000	48836	00007f7a5504f000	48836	48836	rw---	[	anon	]
00007f7ba5092000	48568	00007f7ba5092000	48568	48568	rw---	[	anon	]
00007f7c1d0b7000	48420	00007f7c1d0b7000	2788	2788	rw---	[	anon	]
00007f7b7512d000	47948	00007f7b7512d000	47948	47948	rw---	[	anon	]
00007f7bdc5d5000	47860	00007f7bdc5d5000	228	228	rw---	[	anon	]
00007f7b45174000	47664	00007f7b45174000	46612	46612	rw---	[	anon	]
00007f7d18000000	47288	00007f7d18000000	3696	3696	rw---	[	anon	]
00007f7c551e3000	47220	00007f7c551e3000	5104	5104	rw---	[	anon	]
00007f79cd322000	45944	00007f79cd322000	45944	45944	rw---	[	anon	]
00007f7ad5418000	44960	00007f7ad5418000	44960	44960	rw---	[	anon	]
00007f780d513000	43956	#N/A	0	0	-----	[	anon	]
00007f7a70000000	43916	00007f7a70000000	43916	43916	rw---	[	anon	]
00007f7b40000000	43872	00007f7b40000000	42708	42708	rw---	[	anon	]
00007f7a0be89000	43624	00007f7a0be89000	43624	43624	rw---	[	anon	]
00007f7dc9164000	43616	00007f7dc9164000	0	0	-----	[	anon	]
00007f7d2557d000	43532	00007f7d2557d000	1140	1140	rw---	[	anon	]
00007f78a55ce000	43208	00007f78a55ce000	43208	43208	rw---	[	anon	]
00007f78555e6000	43112	#N/A	43112	43112	rw---	[	anon	]
00007f7b68000000	43028	00007f7b68000000	43028	43028	rw---	[	anon	]
00007f7b10000000	42844	00007f7b10000000	42844	42844	rw---	[	anon	]
00007f7a38000000	42816	00007f7a38000000	42816	42816	rw---	[	anon	]
00007f7dd8000000	42596	00007f7dd8000000	0	0	rw---	[	anon	]
00007f7858000000	42380	#N/A	42380	42380	rw---	[	anon	]
00007f7c38000000	42096	00007f7c38000000	2292	2292	rw---	[	anon	]
00007f7cb0000000	41920	00007f7cb0000000	5256	5256	rw---	[	anon	]
00007f7b28e25000	41812	00007f7b28e25000	41812	41812	rw---	[	anon	]
00007f7a05744000	41712	00007f7a05744000	41712	41712	rw---	[	anon	]
00007f7b72917000	40940	00007f7b72917000	40940	40940	rw---	[	anon	]
00007f7c90000000	40780	00007f7c90000000	1220	1220	rw---	[	anon	]
00007f7b70000000	40692	00007f7b70000000	40692	40692	rw---	[	anon	]
00007f7a1585b000	40596	00007f7a1585b000	40596	40596	rw---	[	anon	]
00007f7a7d889000	40412	00007f7a7d889000	40412	40412	rw---	[	anon	]
00007f79e8000000	39932	00007f79e8000000	39932	39932	rw---	[	anon	]
00007f7a99480000	39796	00007f7a99480000	39796	39796	rw---	[	anon	]
00007f7b42aec000	39400	00007f7b42aec000	39076	39076	rw---	[	anon	]
00007f7aa8000000	39196	00007f7aa8000000	39196	39196	rw---	[	anon	]
00007f7cbce31000	39076	00007f7cbce31000	4124	4124	rw---	[	anon	]
00007f7af0000000	38560	00007f7af0000000	38560	38560	rw---	[	anon	]
00007f7cf8000000	38328	00007f7cf8000000	36864	36864	rw---	[	anon	]
00007f7964f81000	37544	00007f7964f81000	37544	37544	rw---	[	anon	]
00007f7b80000000	37452	00007f7b80000000	37256	37256	rw---	[	anon	]
00007f7b6dc01000	36860	00007f7b6dc01000	36860	36860	rw---	[	anon	]
00007f7f08849000	36684	00007f7f08849000	24400	24400	rw---	[	anon	]
00007f7bed73d000	36540	00007f7bed73d000	2556	2556	rw---	[	anon	]
00007f7d00000000	36528	00007f7d00000000	34940	34940	rw---	[	anon	]
00007f7c8c964000	36472	00007f7c8c964000	2672	2672	rw---	[	anon	]
00007f7b0428f000	36212	00007f7b0428f000	36212	36212	rw---	[	anon	]
00007f7beb375000	35844	00007f7beb375000	4252	4252	rw---	[	anon	]
00007f7be86b8000	35460	00007f7be86b8000	472	472	rw---	[	anon	]
00007f786dd7b000	35348	#N/A	35348	35348	rw---	[	anon	]
00007f7b58000000	35108	00007f7b58000000	35108	35108	rw---	[	anon	]
00007f7b25a07000	34728	00007f7b25a07000	34728	34728	rw---	[	anon	]
00007f7c28000000	34120	00007f7c28000000	1944	1944	rw---	[	anon	]
00007f7b4813d000	33980	00007f7b4813d000	33980	33980	rw---	[	anon	]
00007f7a00000000	33200	00007f7a00000000	33200	33200	rw---	[	anon	]
00007f7bada64000	33056	00007f7bada64000	32928	32928	rw---	[	anon	]
00007f7ee125b000	32832	00007f7ee125b000	21268	21268	rw---	[	anon	]
00007f7b23a43000	32372	00007f7b23a43000	32372	32372	rw---	[	anon	]
00007f7eecca0000	32268	00007f7eecca0000	14184	14184	rw---	[	anon	]
00007f7ee4ba4000	32112	00007f7ee4ba4000	11860	11860	rw---	[	anon	]
00007f7853694000	31828	#N/A	31828	31828	rw---	[	anon	]
00007f7976112000	31672	00007f7976112000	31672	31672	rw---	[	anon	]
00007f7a1e15d000	31372	00007f7a1e15d000	31372	31372	rw---	[	anon	]
00007f7ac8000000	31096	00007f7ac8000000	31096	31096	rw---	[	anon	]
00007f7c30000000	31052	00007f7c30000000	20	20	rw---	[	anon	]
00007f795e1c0000	30976	00007f795e1c0000	30976	30976	rw---	[	anon	]
00007f7956220000	30592	00007f7956220000	30592	30592	rw---	[	anon	]
00007f7d98e12000	30212	00007f7d98e12000	10252	10252	rw---	[	anon	]
00007f79c007c000	30208	00007f79c007c000	30208	30208	rw---	[	anon	]
00007f7c16339000	29468	00007f7c16339000	1388	1388	rw---	[	anon	]
00007f7e38000000	28980	00007f7e38000000	484	484	rw---	[	anon	]
00007f79cb0d2000	28680	00007f79cb0d2000	28680	28680	rw---	[	anon	]
00007f7b55bb0000	28208	00007f7b55bb0000	28208	28208	rw---	[	anon	]
00007f7c35854000	27956	00007f7c35854000	1312	1312	rw---	[	anon	]
00007f795478a000	27120	00007f795478a000	27120	27120	rw---	[	anon	]
00007f7b065f3000	26676	00007f7b065f3000	26676	26676	rw---	[	anon	]
00007f795c793000	26644	00007f795c793000	26644	26644	rw---	[	anon	]
00007f7c20000000	26412	00007f7c20000000	808	808	rw---	[	anon	]
00007f79b8000000	25836	00007f79b8000000	25836	25836	rw---	[	anon	]
00007f7a80000000	25204	00007f7a80000000	25204	25204	rw---	[	anon	]
00007f7ca8000000	24868	00007f7ca8000000	96	96	rw---	[	anon	]
00007f7b367f1000	24636	00007f7b367f1000	24636	24636	rw---	[	anon	]
00007f7a30000000	24416	00007f7a30000000	24416	24416	rw---	[	anon	]
00007f7dee854000	24240	00007f7dee854000	24240	24240	rw---	[	anon	]
00007f7c6e85c000	24208	00007f7c6e85c000	812	812	rw---	[	anon	]
00007f7ce8000000	23864	00007f7ce8000000	22528	22528	rw---	[	anon	]
00007f7ec68d0000	23744	00007f7ec68d0000	24	24	rw---	[	anon	]
00007f789e748000	23636	00007f789e748000	23636	23636	rw---	[	anon	]
00007f7c80000000	23468	00007f7c80000000	16	16	rw---	[	anon	]
00007f7a0e926000	23400	00007f7a0e926000	23400	23400	rw---	[	anon	]
00007f7dda9d7000	22692	00007f7dda9d7000	8	8	rw---	[	anon	]
00007f79369fb000	22548	00007f79369fb000	22548	22548	rw---	[	anon	]
00007f7a72b2c000	22484	00007f7a72b2c000	22484	22484	rw---	[	anon	]
00007f7c26a40000	22272	00007f7c26a40000	12	12	rw---	[	anon	]
00007f7a95c2d000	22260	00007f7a95c2d000	22260	22260	rw---	[	anon	]
00007f7b2b77e000	22116	00007f7b2b77e000	22116	22116	rw---	[	anon	]
00007f7caac3b000	21948	00007f7caac3b000	520	520	rw---	[	anon	]
00007f7a28000000	21668	00007f7a28000000	21668	21668	rw---	[	anon	]
00007f7ef0c08000	21408	00007f7ef0c08000	9360	9356	rw---	[	anon	]
00007f7b08553000	21388	00007f7b08553000	21388	21388	rw---	[	anon	]
00007f79b99b6000	21380	00007f79b99b6000	21380	21380	rw---	[	anon	]
00007f78d8000000	21336	00007f78d8000000	21336	21336	rw---	[	anon	]
00007f7c5eb52000	21176	00007f7c5eb52000	1440	1440	rw---	[	anon	]
00007f7ad8000000	20796	00007f7ad8000000	20796	20796	rw---	[	anon	]
00007f7d58f15000	20356	00007f7d58f15000	18452	18452	rw---	[	anon	]
00007f7eea093000	20148	00007f7eea093000	1792	1792	rw---	[	anon	]
00007f7af6c56000	20136	00007f7af6c56000	20136	20136	rw---	[	anon	]
00007f7ca9856000	20072	00007f7ca9856000	0	0	rw---	[	anon	]
00007f7ce0000000	20040	00007f7ce0000000	18516	18516	rw---	[	anon	]
00007f79b0000000	19632	00007f79b0000000	19632	19632	rw---	[	anon	]
00007f7a53cf8000	19632	00007f7a53cf8000	19632	19632	rw---	[	anon	]
00007f783ecf1000	19516	#N/A	19516	19516	rw---	[	anon	]
00007f7a18000000	18576	00007f7a18000000	18576	18576	rw---	[	anon	]
00007f7f10bd6000	18320	00007f7f10bd6000	10788	10788	rw---	[	anon	]
00007f7ca0000000	18200	00007f7ca0000000	1840	1840	rw---	[	anon	]
00007f7f06077000	18140	00007f7f06077000	12300	12300	rw---	[	anon	]
00007f7f11dc9000	17844	00007f7f11dc9000	2940	2940	rw---	[	anon	]
00007f7c08000000	17768	00007f7c08000000	220	220	rw---	[	anon	]
00007f7a98000000	17628	00007f7a98000000	17628	17628	rw---	[	anon	]
00007f7b35293000	17512	00007f7b35293000	17512	17512	rw---	[	anon	]
00007f7928000000	17424	00007f7928000000	17424	17424	rw---	[	anon	]
00007f7b33550000	17144	00007f7b33550000	17144	17144	rw---	[	anon	]
00007f7b9857b000	16848	00007f7b9857b000	16848	16848	rw---	[	anon	]
00007f7c96fe9000	16476	00007f7c96fe9000	0	0	rw---	[	anon	]
00007f7c78000000	16364	00007f7c78000000	2828	2828	rw---	[	anon	]
00007f79a0000000	16316	00007f79a0000000	16316	16316	rw---	[	anon	]
00007f7e97037000	16164	00007f7e97037000	196	196	rw---	[	anon	]
00007f7c6d014000	16056	00007f7c6d014000	752	752	rw---	[	anon	]
00007f7b4f0ca000	15576	00007f7b4f0ca000	15020	15020	rw---	[	anon	]
00007f7b670cc000	15568	00007f7b670cc000	15568	15568	rw---	[	anon	]
00007f7d58000000	15420	00007f7d58000000	12400	12400	rw---	[	anon	]
00007f7998000000	15352	00007f7998000000	15352	15352	rw---	[	anon	]
00007f7ee9154000	15344	00007f7ee9154000	6484	6484	rw---	[	anon	]
1884000	15240	1884000	13252	13252	rw---	[	anon	]
00007f7c5d86b000	15152	00007f7c5d86b000	8	8	rw---	[	anon	]
00007f7a88000000	15000	00007f7a88000000	15000	15000	rw---	[	anon	]
00007f7a971f4000	14384	00007f7a971f4000	14384	14384	rw---	[	anon	]
00007f7d98000000	14332	00007f7d98000000	12288	12288	rw---	[	anon	]
00007f7bb0000000	14280	00007f7bb0000000	13732	13732	rw---	[	anon	]
00007f79a0ff6000	13884	00007f79a0ff6000	13884	13884	rw---	[	anon	]
00007f7aff28e000	13768	00007f7aff28e000	13768	13768	rw---	[	anon	]
00007f7be0994000	13628	00007f7be0994000	92	92	rw---	[	anon	]
00007f79af13f000	13368	00007f79af13f000	13368	13368	rw---	[	anon	]
00007f78d0000000	13104	00007f78d0000000	13104	13104	rw---	[	anon	]
00007f79f0000000	12980	00007f79f0000000	12980	12980	rw---	[	anon	]
00007f7c10000000	12888	00007f7c10000000	348	348	rw---	[	anon	]
00007f79f6d0d000	12708	00007f79f6d0d000	12708	12708	rw---	[	anon	]
00007f7c373c5000	12524	00007f7c373c5000	1408	1408	rw---	[	anon	]
00007f7f052b0000	12460	00007f7f052b0000	2060	2060	rw---	[	anon	]
00007f7b34678000	12092	00007f7b34678000	12092	12092	rw---	[	anon	]
00007f7bdf493000	11700	00007f7bdf493000	8	8	rw---	[	anon	]
00007f7eeee77000	11180	00007f7eeee77000	220	220	rw---	[	anon	]
00007f7bc0000000	11100	00007f7bc0000000	8944	8944	rw---	[	anon	]
00007f7a90000000	11080	00007f7a90000000	11080	11080	rw---	[	anon	]
00007f7b28000000	10984	00007f7b28000000	10984	10984	rw---	[	anon	]
00007f7d1ae73000	10540	00007f7d1ae73000	8200	8200	rw---	[	anon	]
00007f7f003fb000	10240	00007f7f003fb000	24	24	rw---	[	anon	]
00007f7f00dfc000	10240	00007f7f00dfc000	20	20	rw---	[	anon	]
00007f7f017fd000	10240	00007f7f017fd000	20	20	rw---	[	anon	]
00007f7f021fe000	10240	00007f7f021fe000	24	24	rw---	[	anon	]
00007f7f02bff000	10240	00007f7f02bff000	28	28	rw---	[	anon	]
00007f7f03600000	10240	00007f7f03600000	2048	2048	rw---	[	anon	]
00007f7f1c3fb000	10240	00007f7f1c3fb000	20	20	rw---	[	anon	]
00007f7f1cdfc000	10240	00007f7f1cdfc000	28	28	rw---	[	anon	]
00007f7f1d7fd000	10240	00007f7f1d7fd000	20	20	rw---	[	anon	]
00007f7f1e1fe000	10240	00007f7f1e1fe000	20	20	rw---	[	anon	]
00007f7f1ebff000	10240	00007f7f1ebff000	20	20	rw---	[	anon	]
00007f7f1f600000	10240	00007f7f1f600000	2048	2048	rw---	[	anon	]
00007f7f2c3e8000	10240	00007f7f2c3e8000	8	8	rw---	[	anon	]
00007f7f2cde9000	10240	00007f7f2cde9000	8	8	rw---	[	anon	]
00007f7f2d7ea000	10240	00007f7f2d7ea000	8	8	rw---	[	anon	]
00007f7f2e1eb000	10240	00007f7f2e1eb000	32	32	rw---	[	anon	]
00007f796762b000	10068	00007f796762b000	10068	10068	rw---	[	anon	]
00007f7c8f64f000	9924	00007f7c8f64f000	0	0	rw---	[	anon	]
00007f7c2a3b2000	9868	00007f7c2a3b2000	444	444	rw---	[	anon	]
00007f7ee7663000	9844	00007f7ee7663000	692	692	rw---	[	anon	]
00007f7cbf6c4000	9456	00007f7cbf6c4000	2416	2416	rw---	[	anon	]
00007f7c8ed14000	9328	00007f7c8ed14000	156	156	rw---	[	anon	]
00007f7ef2ee4000	9036	00007f7ef2ee4000	2432	2432	rw---	[	anon	]
00007f7eeb731000	9020	00007f7eeb731000	548	548	rw---	[	anon	]
00007f7be0000000	8648	00007f7be0000000	1068	1068	rw---	[	anon	]
00007f7ef37b7000	8484	00007f7ef37b7000	0	0	-----	[	anon	]
00007f7c6dfda000	8480	00007f7c6dfda000	356	356	rw---	[	anon	]
00007f7c091d2000	8284	00007f7c091d2000	484	484	rw---	[	anon	]
00007f7aebeb8000	8196	00007f7aebeb8000	8196	8196	rw---	[	anon	]
00007f7abf82b000	8020	00007f7abf82b000	8020	8020	rw---	[	anon	]
00007f7b8f839000	7964	00007f7b8f839000	7900	7900	rw---	[	anon	]
00007f79f64ee000	7836	00007f79f64ee000	7836	7836	rw---	[	anon	]
00007f7e10000000	7828	00007f7e10000000	0	0	rw---	[	anon	]
00007f7f1385b000	7828	00007f7f1385b000	4096	4096	rw---	[	anon	]
00007f7c3509d000	7636	00007f7c3509d000	68	68	rw---	[	anon	]
00007f7c927f7000	7508	00007f7c927f7000	0	0	rw---	[	anon	]
00007f7a90ad6000	7488	00007f7a90ad6000	7488	7488	rw---	[	anon	]
00007f7ee8a27000	7212	00007f7ee8a27000	5788	5788	rw---	[	anon	]
00007f7c26339000	7060	00007f7c26339000	0	0	rw---	[	anon	]
00007f7ef20fd000	6980	00007f7ef20fd000	2672	2672	rw---	[	anon	]
00007f7edf938000	6944	00007f7edf938000	0	0	-----	[	anon	]
00007f7938000000	6840	00007f7938000000	6840	6840	rw---	[	anon	]
00007f7bf8000000	6828	00007f7bf8000000	676	676	rw---	[	anon	]
00007f7eef962000	6776	00007f7eef962000	0	0	-----	[	anon	]
00007f7be8000000	6764	00007f7be8000000	1272	1272	rw---	[	anon	]
00007f7da796e000	6728	00007f7da796e000	0	0	rw---	[	anon	]
00007f7ed7971000	6716	00007f7ed7971000	0	0	-----	[	anon	]
00007f7f13064000	6656	00007f7f13064000	60	60	rw---	[	anon	]
00007f7c099fb000	6604	00007f7c099fb000	696	696	rw---	[	anon	]
00007f7ba0000000	6336	00007f7ba0000000	6336	6336	rw---	[	anon	]
00007f79f79f4000	6192	00007f79f79f4000	6192	6192	rw---	[	anon	]
00007f7d60000000	6044	00007f7d60000000	4	4	rw---	[	anon	]
00007f7bead75000	6028	00007f7bead75000	312	312	rw---	[	anon	]
00007f79ccd1c000	6000	00007f79ccd1c000	6000	6000	rw---	[	anon	]
00007f7b57769000	5740	00007f7b57769000	5740	5740	rw---	[	anon	]
00007f7a4f7a2000	5616	00007f7a4f7a2000	5616	5616	rw---	[	anon	]
00007f7ef2993000	5400	00007f7ef2993000	2336	2336	rw---	[	anon	]
00007f7808000000	5324	#N/A	5324	5324	rw---	[	anon	]
00007f7ee6c0e000	5300	00007f7ee6c0e000	1188	1188	rw---	[	anon	]
00007f7befaed000	5196	00007f7befaed000	52	52	rw---	[	anon	]
00007f7bafb1c000	5008	00007f7bafb1c000	5008	5008	rw---	[	anon	]
00007f7b98000000	4884	00007f7b98000000	4884	4884	rw---	[	anon	]
00007f7ee3b46000	4840	00007f7ee3b46000	2588	2588	rw---	[	anon	]
00007f7a05111000	4824	00007f7a05111000	4824	4824	rw---	[	anon	]
00007f7b08000000	4732	00007f7b08000000	4732	4732	rw---	[	anon	]
00007f7ee3502000	4720	00007f7ee3502000	128	128	rw---	[	anon	]
00007f7f0ac27000	4380	00007f7f0ac27000	3368	3368	rw---	[	anon	]
00007f7f0b37c000	4368	00007f7f0b37c000	2388	2388	rw---	[	anon	]
00007f7b363b0000	4316	00007f7b363b0000	4316	4316	rw---	[	anon	]
00007f7ee045e000	4220	00007f7ee045e000	3476	3476	rw---	[	anon	]
00007f7e18000000	4144	00007f7e18000000	0	0	rw---	[	anon	]
00007f7b27bfb000	4116	00007f7b27bfb000	4116	4116	rw---	[	anon	]
00007f7dcbbfc000	4112	00007f7dcbbfc000	0	0	-----	[	anon	]
00007f7ba4c63000	4048	00007f7ba4c63000	4048	4048	rw---	[	anon	]
00007f7ee4000000	4008	00007f7ee4000000	4008	4008	rw---	[	anon	]
00007f7f0728d000	3996	00007f7f0728d000	3880	3880	rw---	[	anon	]
00007f7bea95c000	3936	00007f7bea95c000	0	0	rw---	[	anon	]
00007f7c5e7b5000	3688	00007f7c5e7b5000	516	516	rw---	[	anon	]
00007f7ef0408000	3520	00007f7ef0408000	3520	3520	rw---	[	anon	]
00007f7f0ba55000	3432	00007f7f0ba55000	796	796	rw---	[	anon	]
00007f7ef00b1000	3368	00007f7ef00b1000	3312	3312	rw---	[	anon	]
00007f7f04000000	3260	00007f7f04000000	2980	2980	rw---	[	anon	]
00007f7ee7145000	3228	00007f7ee7145000	540	540	rw---	[	anon	]
00007f7b28af8000	3184	00007f7b28af8000	3184	3184	rw---	[	anon	]
00007f7f04b93000	3152	00007f7f04b93000	3152	3152	rw---	[	anon	]
00007f7f0b076000	3032	00007f7f0b076000	1796	1796	rw---	[	anon	]
00007f7eeb447000	2964	00007f7eeb447000	0	0	rw---	[	anon	]
00007f7ef4024000	2960	00007f7ef4024000	0	0	-----	[	anon	]
00007f7ef8024000	2960	00007f7ef8024000	0	0	-----	[	anon	]
00007f7efc024000	2960	00007f7efc024000	0	0	-----	[	anon	]
00007f7a9916c000	2940	00007f7a9916c000	2940	2940	rw---	[	anon	]
00007f7dc82b8000	2904	00007f7dc82b8000	4	4	rw---	[	anon	]
00007f7eec3f1000	2892	00007f7eec3f1000	2600	2600	rw---	[	anon	]
00007f7ba07b0000	2748	00007f7ba07b0000	2748	2748	rw---	[	anon	]
00007f7a4fd57000	2724	00007f7a4fd57000	2724	2724	rw---	[	anon	]
00007f7ee0000000	2632	00007f7ee0000000	2476	2476	rw---	[	anon	]
00007f7b57d7a000	2584	00007f7b57d7a000	2584	2584	rw---	[	anon	]
00007f7dc8033000	2580	00007f7dc8033000	0	0	rw---	[	anon	]
00007f7f0b7cf000	2560	00007f7f0b7cf000	0	0	rw---	[	anon	]
00007f7ee3276000	2524	00007f7ee3276000	632	632	rw---	[	anon	]
00007f7eec84c000	2504	00007f7eec84c000	2444	2444	rw---	[	anon	]
00007f7ee8000000	2468	00007f7ee8000000	2292	2292	rw---	[	anon	]
00007f7ef0990000	2356	00007f7ef0990000	2248	2248	rw---	[	anon	]
00007f7d4fdc2000	2296	00007f7d4fdc2000	2052	2052	rw---	[	anon	]
00007f7f10107000	2252	00007f7f10107000	2064	2064	rw---	[	anon	]
00007f7ee0fe0000	2240	00007f7ee0fe0000	2108	2108	rw---	[	anon	]
00007f7a40000000	2236	00007f7a40000000	2236	2236	rw---	[	anon	]
00007f7f10888000	2212	00007f7f10888000	2212	2212	rw---	[	anon	]
00007f7f04eac000	2180	00007f7f04eac000	1976	1976	rw---	[	anon	]
00007f7dc87c2000	2160	00007f7dc87c2000	76	76	rw---	[	anon	]
00007f7eec1c4000	2160	00007f7eec1c4000	2104	2104	rw---	[	anon	]
00007f7d10000000	2148	00007f7d10000000	2048	2048	rw---	[	anon	]
00007f7f08000000	2056	00007f7f08000000	1824	1824	rw---	[	anon	]
00007f7f2f164000	2048	00007f7f2f164000	0	0	-----	libdb-4.7.so		
00007f7f2f574000	2048	00007f7f2f574000	0	0	-----	libcrammd5.so.2.0.23		
00007f7f2fb92000	2048	00007f7f2fb92000	0	0	-----	libsyslogformat.so		
00007f7f304ea000	2048	00007f7f304ea000	0	0	-----	libkafka.so		
00007f7f30af8000	2048	00007f7f30af8000	0	0	-----	libcrypt-2.12.so		
00007f7f313b2000	2048	00007f7f313b2000	0	0	-----	libnspr4.so		
00007f7f31d2d000	2048	00007f7f31d2d000	0	0	-----	libnss3.so		
00007f7f321b2000	2048	00007f7f321b2000	0	0	-----	libssl3.so		
00007f7f32aa0000	2048	00007f7f32aa0000	0	0	-----	libhttp.so		
00007f7f32f31000	2048	00007f7f32f31000	0	0	-----	libbasicfuncs.so		
00007f7f33140000	2048	00007f7f33140000	0	0	-----	libjson-c.so.3.0.1		
00007f7f33554000	2048	00007f7f33554000	0	0	-----	libappmodel.so		
00007f7f341bc000	2048	00007f7f341bc000	0	0	-----	libresolv-2.12.so		
00007f7f343e9000	2048	00007f7f343e9000	0	0	-----	libk5crypto.so.3.1		
00007f7f34b18000	2048	00007f7f34b18000	0	0	-----	libgssapi_krb5.so.2.2		
00007f7f34ed5000	2048	00007f7f34ed5000	0	0	-----	libcrypto.so.1.0.1e		
00007f7f35162000	2048	00007f7f35162000	0	0	-----	libssl.so.1.0.1e		
00007f7f35717000	2048	00007f7f35717000	0	0	-----	libpthread-2.12.so		
00007f7f3591f000	2048	00007f7f3591f000	0	0	-----	libdl-2.12.so		
00007f7f35f44000	2048	00007f7f35f44000	0	0	-----	libevtlog-3.23.so.0.0.0		
00007f7f3625a000	2048	00007f7f3625a000	0	0	-----	libglib-2.0.so.0.2800.8		
00007f7f36d55000	2048	00007f7f36d55000	0	0	-----	libsyslog-ng-3.23.so.0.0.0		
00007f7f2c1e6000	2044	00007f7f2c1e6000	0	0	-----	libnss_dns-2.12.so		
00007f7f2ebef000	2044	00007f7f2ebef000	0	0	-----	libanonymous.so.2.0.23		
00007f7f2edf4000	2044	00007f7f2edf4000	0	0	-----	libplain.so.2.0.23		
00007f7f2f36f000	2044	00007f7f2f36f000	0	0	-----	libsasldb.so.2.0.23		
00007f7f2f782000	2044	00007f7f2f782000	0	0	-----	libdigestmd5.so.2.0.23		
00007f7f2f987000	2044	00007f7f2f987000	0	0	-----	liblogin.so.2.0.23		
00007f7f2fdae000	2044	00007f7f2fdae000	0	0	-----	libaffile.so		
00007f7f2ffd2000	2044	00007f7f2ffd2000	0	0	-----	libafsocket.so		
00007f7f302c6000	2044	00007f7f302c6000	0	0	-----	librdkafka.so.1		
00007f7f306ee000	2044	00007f7f306ee000	0	0	-----	libconfgen.so		
00007f7f308f0000	2044	00007f7f308f0000	0	0	-----	libfreebl3.so		
00007f7f30d41000	2044	00007f7f30d41000	0	0	-----	libsasl2.so.2.0.23		
00007f7f30f50000	2044	00007f7f30f50000	0	0	-----	liblber-2.4.so.2.10.3		
00007f7f31178000	2044	00007f7f31178000	0	0	-----	libssh2.so.1.0.1		
00007f7f315bc000	2044	00007f7f315bc000	0	0	-----	libplc4.so		
00007f7f317c0000	2044	00007f7f317c0000	0	0	-----	libplds4.so		
00007f7f319e9000	2044	00007f7f319e9000	0	0	-----	libnssutil3.so		
00007f7f31f61000	2044	00007f7f31f61000	0	0	-----	libsmime3.so		
00007f7f32406000	2044	00007f7f32406000	0	0	-----	libldap-2.4.so.2.10.3		
00007f7f3263b000	2044	00007f7f3263b000	0	0	-----	libidn.so.11.6.1		
00007f7f3288e000	2044	00007f7f3288e000	0	0	-----	libcurl.so.4.1.1		
00007f7f32d25000	2044	00007f7f32d25000	0	0	-----	libm-2.12.so		
00007f7f3334c000	2044	00007f7f3334c000	0	0	-----	libjson-plugin.so		
00007f7f33762000	2044	00007f7f33762000	0	0	-----	libnss_files-2.12.so		
00007f7f33980000	2044	00007f7f33980000	0	0	-----	libselinux.so.1		
00007f7f33b84000	2044	00007f7f33b84000	0	0	-----	libkeyutils.so.1.3		
00007f7f33d8f000	2044	00007f7f33d8f000	0	0	-----	libkrb5support.so.0.1		
00007f7f33fa5000	2044	00007f7f33fa5000	0	0	-----	libz.so.1.2.3		
00007f7f345ef000	2044	00007f7f345ef000	0	0	-----	libcom_err.so.2.1		
00007f7f348cc000	2044	00007f7f348cc000	0	0	-----	libkrb5.so.3.3		
00007f7f354f7000	2044	00007f7f354f7000	0	0	-----	libc-2.12.so		
00007f7f35b3e000	2044	00007f7f35b3e000	0	0	-----	libpcre.so.1.2.8		
00007f7f35d41000	2044	00007f7f35d41000	0	0	-----	libsecret-storage.so.0.0.0		
00007f7f36463000	2044	00007f7f36463000	0	0	-----	librt-2.12.so		
00007f7f36668000	2044	00007f7f36668000	0	0	-----	libgthread-2.0.so.0.2800.8		
00007f7f3686b000	2044	00007f7f3686b000	0	0	-----	libgmodule-2.0.so.0.2800.8		
00007f7f36a81000	2044	00007f7f36a81000	0	0	-----	libnsl-2.12.so		
00007f7ee826a000	2008	00007f7ee826a000	2008	2008	rw---	[	anon	]
00007f7ad5225000	1996	00007f7ad5225000	1996	1996	rw---	[	anon	]
00007f7ee7475000	1968	00007f7ee7475000	460	460	rw---	[	anon	]
00007f796742c000	1960	00007f796742c000	1960	1960	rw---	[	anon	]
00007f7f04573000	1952	00007f7f04573000	1952	1952	rw---	[	anon	]
00007f7f050cd000	1932	00007f7f050cd000	96	96	rw---	[	anon	]
00007f7eecabe000	1928	00007f7eecabe000	1072	1072	rw---	[	anon	]
00007f7f0475b000	1928	00007f7f0475b000	1928	1928	rw---	[	anon	]
00007f7f04389000	1892	00007f7f04389000	1892	1892	rw---	[	anon	]
00007f7dc8ae5000	1848	00007f7dc8ae5000	0	0	rw---	[	anon	]
00007f7ef27ce000	1812	00007f7ef27ce000	52	52	rw---	[	anon	]
00007f7ee0e1e000	1796	00007f7ee0e1e000	532	532	rw---	[	anon	]
00007f7c2a1ae000	1784	00007f7c2a1ae000	0	0	rw---	[	anon	]
00007f7f34d1b000	1768	00007f7f34d1b000	100	0	r-x--	libcrypto.so.1.0.1e		
00007f7eeec23000	1764	00007f7eeec23000	0	0	rw---	[	anon	]
00007f7ee0a03000	1760	00007f7ee0a03000	1116	1116	rw---	[	anon	]
00007f7f08696000	1720	00007f7f08696000	1720	1720	rw---	[	anon	]
00007f79afe56000	1704	00007f79afe56000	1704	1704	rw---	[	anon	]
00007f7ee399e000	1696	00007f7ee399e000	60	60	rw---	[	anon	]
00007f7ee49fb000	1696	00007f7ee49fb000	1632	1632	rw---	[	anon	]
00007f7be7e59000	1692	00007f7be7e59000	24	24	rw---	[	anon	]
00007f7f05edb000	1648	00007f7f05edb000	0	0	rw---	[	anon	]
00007f7edc38f000	1640	00007f7edc38f000	292	292	rw---	[	anon	]
00007f7ee029d000	1596	00007f7ee029d000	1596	1596	rw---	[	anon	]
00007f7f3536c000	1580	00007f7f3536c000	720	0	r-x--	libc-2.12.so		
00007f7cbf509000	1572	00007f7cbf509000	64	64	rw---	[	anon	]
00007f7dc8e6b000	1544	00007f7dc8e6b000	44	44	rw---	[	anon	]
00007f789fe80000	1536	00007f789fe80000	1536	1536	rw---	[	anon	]
00007f7f0bdaf000	1528	00007f7f0bdaf000	1216	1216	rw---	[	anon	]
00007f7a055c7000	1524	00007f7a055c7000	1524	1524	rw---	[	anon	]
00007f7ee44b1000	1500	00007f7ee44b1000	1440	1440	rw---	[	anon	]
00007f7c5d6fa000	1476	00007f7c5d6fa000	76	76	rw---	[	anon	]
00007f7f2eff5000	1468	00007f7f2eff5000	16	0	r-x--	libdb-4.7.so		
00007f7f136f2000	1420	00007f7f136f2000	0	0	rw---	[	anon	]
00007f7b727bd000	1384	00007f7b727bd000	1384	1384	rw---	[	anon	]
00007f7ee8550000	1380	00007f7ee8550000	1320	1320	rw---	[	anon	]
00007f7f0835d000	1368	00007f7f0835d000	1308	1308	rw---	[	anon	]
00007f7f07dd0000	1360	00007f7f07dd0000	304	304	rw---	[	anon	]
00007f7f31bf0000	1268	00007f7f31bf0000	112	0	r-x--	libnss3.so		
00007f7ee0cdf000	1244	00007f7ee0cdf000	720	720	rw---	[	anon	]
00007f7b48000000	1224	00007f7b48000000	1224	1224	rw---	[	anon	]
00007f7ba065f000	1220	00007f7ba065f000	1220	1220	rw---	[	anon	]
00007f7f0493d000	1192	00007f7f0493d000	1192	1192	rw---	[	anon	]
00007f7ee08b7000	1188	00007f7ee08b7000	528	528	rw---	[	anon	]
00007f7ef0778000	1164	00007f7ef0778000	1164	1164	rw---	[	anon	]
00007f7be0872000	1160	00007f7be0872000	0	0	rw---	[	anon	]
00007f7dc8675000	1148	00007f7dc8675000	20	20	rw---	[	anon	]
00007f7dee6f7000	1148	00007f7dee6f7000	1148	1148	rw---	[	anon	]
00007f7edc000000	1140	00007f7edc000000	44	44	rw---	[	anon	]
00007f7ee0bc0000	1128	00007f7ee0bc0000	1128	1128	rw---	[	anon	]
00007f7f10761000	1124	00007f7f10761000	1124	1124	rw---	[	anon	]
00007f7a3a9d0000	1112	00007f7a3a9d0000	1112	1112	rw---	[	anon	]
00007f7f12f40000	1112	00007f7f12f40000	12	12	rw---	[	anon	]
00007f7f36145000	1108	00007f7f36145000	260	0	r-x--	libglib-2.0.so.0.2800.8		
00007f7ed3eec000	1104	00007f7ed3eec000	0	0	-----	[	anon	]
00007f7a402cc000	1056	00007f7a402cc000	1056	1056	rw---	[	anon	]
00007f7f1054a000	1052	00007f7f1054a000	1052	1052	rw---	[	anon	]
00007f7f10ac7000	1048	00007f7f10ac7000	1020	1020	rw---	[	anon	]
00007f7eec000000	1044	00007f7eec000000	1044	1044	rw---	[	anon	]
00007f7f0781b000	1040	00007f7f0781b000	0	0	rw---	[	anon	]
00007f7f37063000	1024	00007f7f37063000	20	20	rw---	[	anon	]
00007f7ee6b04000	1020	00007f7ee6b04000	4	4	rw---	[	anon	]
00007f7f084f9000	1008	00007f7f084f9000	1008	1008	rw---	[	anon	]
00007f7ee48f3000	1004	00007f7ee48f3000	1004	1004	rw---	[	anon	]
00007f7b129d7000	1000	00007f7b129d7000	1000	1000	rw---	[	anon	]
00007f7f301d6000	960	00007f7f301d6000	360	0	r-x--	librdkafka.so.1		
00007f7edc29f000	956	00007f7edc29f000	36	36	rw---	[	anon	]
00007f7f04a8a000	956	00007f7f04a8a000	896	896	rw---	[	anon	]
00007f7ee86a9000	944	00007f7ee86a9000	944	944	rw---	[	anon	]
00007f7d1ff16000	936	00007f7d1ff16000	0	0	rw---	[	anon	]
00007f7f07a8b000	936	00007f7f07a8b000	8	8	rw---	[	anon	]
00007f7f07735000	920	00007f7f07735000	0	0	rw---	[	anon	]
00007f7dc9086000	888	00007f7dc9086000	28	28	rw---	[	anon	]
00007f7f10672000	888	00007f7f10672000	888	888	rw---	[	anon	]
00007f7ee8850000	880	00007f7ee8850000	880	880	rw---	[	anon	]
00007f7f347f0000	880	00007f7f347f0000	12	0	r-x--	libkrb5.so.3.3		
00007f7edc1c1000	872	00007f7edc1c1000	24	24	rw---	[	anon	]
00007f7ee8477000	868	00007f7ee8477000	868	868	rw---	[	anon	]
00007f7f0bf2d000	844	00007f7f0bf2d000	0	0	-----	[	anon	]
00007f7f10000000	840	00007f7f10000000	780	780	rw---	[	anon	]
00007f7f36c84000	836	00007f7f36c84000	432	0	r-x--	libsyslog-ng-3.23.so.0.0.0		
00007f7dc89e4000	832	00007f7dc89e4000	32	32	rw---	[	anon	]
00007f79bae97000	816	00007f79bae97000	816	816	rw---	[	anon	]
00007f7ee47c9000	816	00007f7ee47c9000	816	816	rw---	[	anon	]
00007f7bed676000	796	00007f7bed676000	0	0	rw---	[	anon	]
00007f7eec105000	764	00007f7eec105000	764	764	rw---	[	anon	]
00007f7f07b7b000	764	00007f7f07b7b000	0	0	rw---	[	anon	]
00007f7f07f24000	764	00007f7f07f24000	0	0	rw---	[	anon	]
00007f7b984c5000	728	00007f7b984c5000	728	728	rw---	[	anon	]
00007f7b0849f000	720	00007f7b0849f000	720	720	rw---	[	anon	]
00007f7dee644000	716	00007f7dee644000	716	716	rw---	[	anon	]
00007f7d1b8be000	708	00007f7d1b8be000	16	16	rw---	[	anon	]
00007f7dc8cb3000	704	00007f7dc8cb3000	16	16	rw---	[	anon	]
00007f7cbf45a000	700	00007f7cbf45a000	180	180	rw---	[	anon	]
00007f7ef0000000	700	00007f7ef0000000	580	580	rw---	[	anon	]
00007f7f079c1000	700	00007f7f079c1000	4	4	rw---	[	anon	]
00007f7f1033a000	700	00007f7f1033a000	700	700	rw---	[	anon	]
00007f7c0a06e000	684	00007f7c0a06e000	4	4	rw---	[	anon	]
00007f7af25a8000	680	00007f7af25a8000	680	680	rw---	[	anon	]
00007f7a8ff5b000	660	00007f7a8ff5b000	660	660	rw---	[	anon	]
00007f7edc11d000	656	00007f7edc11d000	16	16	rw---	[	anon	]
00007f7f0791f000	648	00007f7f0791f000	0	0	rw---	[	anon	]
00007f7a4022f000	628	00007f7a4022f000	628	628	rw---	[	anon	]
00007f7ee4407000	616	00007f7ee4407000	616	616	rw---	[	anon	]
00007f7dc8fed000	612	00007f7dc8fed000	52	52	rw---	[	anon	]
00007f79b132c000	608	00007f79b132c000	608	608	rw---	[	anon	]
00007f7aaa647000	608	00007f7aaa647000	608	608	rw---	[	anon	]
00007f7ef08f3000	608	00007f7ef08f3000	608	608	rw---	[	anon	]
00007f7a403d4000	600	00007f7a403d4000	600	600	rw---	[	anon	]
00007f7ee87b3000	600	00007f7ee87b3000	600	600	rw---	[	anon	]
00007f7f10467000	600	00007f7f10467000	600	600	rw---	[	anon	]
00007f7cd31e1000	592	00007f7cd31e1000	0	0	rw---	[	anon	]
00007f7eec72f000	592	00007f7eec72f000	592	592	rw---	[	anon	]
00007f7f08212000	588	00007f7f08212000	588	588	rw---	[	anon	]
00007f78d0ccc000	572	00007f78d0ccc000	572	572	rw---	[	anon	]
00007f7dc8ddd000	568	00007f7dc8ddd000	20	20	rw---	[	anon	]
00007f7dc858e000	564	00007f7dc858e000	20	20	rw---	[	anon	]
00007f7f07c3a000	564	00007f7f07c3a000	0	0	rw---	[	anon	]
00007f7eeeddc000	552	00007f7eeeddc000	0	0	rw---	[	anon	]
00007f7f07cc7000	552	00007f7f07cc7000	0	0	rw---	[	anon	]
00007f7f082b7000	532	00007f7f082b7000	532	532	rw---	[	anon	]
00007f7b2b6fa000	528	00007f7b2b6fa000	528	528	rw---	[	anon	]
00007f7ad944f000	524	00007f7ad944f000	524	524	rw---	[	anon	]
00007f7c162b6000	524	00007f7c162b6000	472	472	rw---	[	anon	]
00007f7ed0000000	524	00007f7ed0000000	396	396	rw---	[	anon	]
00007f7f32ca2000	524	00007f7f32ca2000	20	0	r-x--	libm-2.12.so		
00007f7b09a36000	512	00007f7b09a36000	512	512	rw---	[	anon	]
00007f7ec6850000	512	00007f7ec6850000	16	16	rw---	[	anon	]
00007f7f07d51000	508	00007f7f07d51000	0	0	rw---	[	anon	]
00007f79f7976000	504	00007f79f7976000	504	504	rw---	[	anon	]
00007f7c5e737000	504	00007f7c5e737000	256	256	rw---	[	anon	]
00007f79b993b000	492	00007f79b993b000	492	492	rw---	[	anon	]
00007f7bf86ab000	488	00007f7bf86ab000	412	412	rw---	[	anon	]
00007f7dc8d63000	488	00007f7dc8d63000	4	4	rw---	[	anon	]
00007f79c1dfc000	484	00007f79c1dfc000	484	484	rw---	[	anon	]
00007f79f6c95000	480	00007f79f6c95000	480	480	rw---	[	anon	]
00007f7c0915a000	480	00007f7c0915a000	0	0	rw---	[	anon	]
00007f7edc530000	480	00007f7edc530000	16	16	rw---	[	anon	]
00007f7b57d04000	472	00007f7b57d04000	472	472	rw---	[	anon	]
00007f7bb0df2000	460	00007f7bb0df2000	460	460	rw---	[	anon	]
00007f7bafaac000	448	00007f7bafaac000	448	448	rw---	[	anon	]
00007f7c3502d000	448	00007f7c3502d000	0	0	rw---	[	anon	]
00007f7ee4754000	444	00007f7ee4754000	444	444	rw---	[	anon	]
00007f7ee892c000	440	00007f7ee892c000	440	440	rw---	[	anon	]
00007f7eec7d3000	436	00007f7eec7d3000	436	436	rw---	[	anon	]
00007f7d25511000	432	00007f7d25511000	0	0	rw---	[	anon	]
00007f7a9bb5d000	424	00007f7a9bb5d000	424	424	rw---	[	anon	]
00007f7b3460e000	424	00007f7b3460e000	424	424	rw---	[	anon	]
00007f7f076cb000	424	00007f7f076cb000	0	0	rw---	[	anon	]
00007f783ec8a000	412	#N/A	412	412	rw---	[	anon	]
00007f7d023ac000	400	00007f7d023ac000	0	0	rw---	[	anon	]
00007f7ee46b7000	400	00007f7ee46b7000	400	400	rw---	[	anon	]
00007f7f103e9000	400	00007f7f103e9000	400	400	rw---	[	anon	]
00007f7f35100000	392	00007f7f35100000	60	0	r-x--	libssl.so.1.0.1e		
00007f7b55b4f000	388	00007f7b55b4f000	388	388	rw---	[	anon	]
00007f795472d000	372	00007f795472d000	372	372	rw---	[	anon	]
00007f7c2a152000	368	00007f7c2a152000	0	0	rw---	[	anon	]
00007f7ee4628000	368	00007f7ee4628000	368	368	rw---	[	anon	]
00007f7c3a91c000	352	00007f7c3a91c000	0	0	rw---	[	anon	]
00007f79c0025000	348	00007f79c0025000	348	348	rw---	[	anon	]
00007f7f07674000	348	00007f7f07674000	0	0	rw---	[	anon	]
00007f7f085f5000	348	00007f7f085f5000	348	348	rw---	[	anon	]
00007f7aec6b9000	336	00007f7aec6b9000	336	336	rw---	[	anon	]
00007f7f3283b000	332	00007f7f3283b000	0	0	r-x--	libcurl.so.4.1.1		
00007f7b1ffae000	328	00007f7b1ffae000	328	328	rw---	[	anon	]
00007f7ee89ae000	328	00007f7ee89ae000	328	328	rw---	[	anon	]
00007f7ef089b000	328	00007f7ef089b000	328	328	rw---	[	anon	]
00007f7c8c914000	320	00007f7c8c914000	28	28	rw---	[	anon	]
00007f7ba0a5f000	312	00007f7ba0a5f000	312	312	rw---	[	anon	]
00007f7f323b8000	312	00007f7f323b8000	44	0	r-x--	libldap-2.4.so.2.10.3		
00007f7f104fd000	308	00007f7f104fd000	308	308	rw---	[	anon	]
00007f7f32165000	308	00007f7f32165000	56	0	r-x--	libssl3.so		
00007f7b35247000	304	00007f7b35247000	304	304	rw---	[	anon	]
00007f7caabf0000	300	00007f7caabf0000	0	0	rw---	[	anon	]
00007f7ee1210000	300	00007f7ee1210000	300	300	rw---	[	anon	]
00007f7aebe6e000	296	00007f7aebe6e000	296	296	rw---	[	anon	]
00007f7a72ae3000	292	00007f7a72ae3000	292	292	rw---	[	anon	]
00007f79cccd4000	288	00007f79cccd4000	288	288	rw---	[	anon	]
00007f7f0864c000	288	00007f7f0864c000	288	288	rw---	[	anon	]
00007f7be16e3000	284	00007f7be16e3000	0	0	rw---	[	anon	]
00007f7c2a36c000	280	00007f7c2a36c000	0	0	rw---	[	anon	]
00007f789e703000	276	00007f789e703000	276	276	rw---	[	anon	]
00007f7998efe000	276	00007f7998efe000	276	276	rw---	[	anon	]
00007f7d1ae2e000	276	00007f7d1ae2e000	0	0	rw---	[	anon	]
00007f7f04333000	276	00007f7f04333000	276	276	rw---	[	anon	]
00007f7da3633000	272	00007f7da3633000	0	0	rw---	[	anon	]
00007f7dc861b000	272	00007f7dc861b000	0	0	rw---	[	anon	]
00007f79db0c5000	268	00007f79db0c5000	268	268	rw---	[	anon	]
00007f7bada21000	268	00007f7bada21000	268	268	rw---	[	anon	]
00007f7eea050000	268	00007f7eea050000	268	268	rw---	[	anon	]
00007f7c35812000	264	00007f7c35812000	0	0	rw---	[	anon	]
00007f7b3350f000	260	00007f7b3350f000	260	260	rw---	[	anon	]
00007f7bead34000	260	00007f7bead34000	0	0	rw---	[	anon	]
00007f7c2ad55000	260	00007f7c2ad55000	0	0	rw---	[	anon	]
00007f7f34ad7000	260	00007f7f34ad7000	12	0	r-x--	libgssapi_krb5.so.2.2		
00007f7c92f4c000	256	00007f7c92f4c000	4	4	rw---	[	anon	]
00007f7ee4899000	252	00007f7ee4899000	252	252	rw---	[	anon	]
00007f7eec6d0000	252	00007f7eec6d0000	252	252	rw---	[	anon	]
00007f7813b29000	248	#N/A	248	248	rw---	[	anon	]
00007f7b28aba000	248	00007f7b28aba000	248	248	rw---	[	anon	]
00007f7b6708e000	248	00007f7b6708e000	248	248	rw---	[	anon	]
00007f7dda999000	248	00007f7dda999000	0	0	rw---	[	anon	]
00007f7dee816000	248	00007f7dee816000	248	248	rw---	[	anon	]
00007f78555a9000	244	#N/A	244	244	rw---	[	anon	]
00007f7ecbfc3000	244	00007f7ecbfc3000	0	0	-----	[	anon	]
00007f7ba5057000	236	00007f7ba5057000	236	236	rw---	[	anon	]
00007f7cfa56e000	236	00007f7cfa56e000	0	0	rw---	[	anon	]
00007f7b2cd17000	232	00007f7b2cd17000	232	232	rw---	[	anon	]
00007f7c6e822000	232	00007f7c6e822000	0	0	rw---	[	anon	]
00007f7a15822000	228	00007f7a15822000	228	228	rw---	[	anon	]
00007f7a4431d000	228	00007f7a4431d000	228	228	rw---	[	anon	]
00007f7a4fd1e000	228	00007f7a4fd1e000	228	228	rw---	[	anon	]
00007f7a74121000	228	00007f7a74121000	228	228	rw---	[	anon	]
00007f7f31379000	228	00007f7f31379000	64	0	r-x--	libnspr4.so		
00007f7929104000	224	00007f7929104000	224	224	rw---	[	anon	]
00007f7ce974e000	224	00007f7ce974e000	0	0	rw---	[	anon	]
00007f79f64b7000	220	00007f79f64b7000	220	220	rw---	[	anon	]
00007f7b995ef000	220	00007f7b995ef000	220	220	rw---	[	anon	]
00007f7d1326b000	220	00007f7d1326b000	0	0	rw---	[	anon	]
00007f7f0722e000	216	00007f7f0722e000	16	16	rw---	[	anon	]
00007f79760dd000	212	00007f79760dd000	212	212	rw---	[	anon	]
00007f7a99137000	212	00007f7a99137000	212	212	rw---	[	anon	]
00007f7a9944b000	212	00007f7a9944b000	212	212	rw---	[	anon	]
00007f7f100d2000	212	00007f7f100d2000	212	212	rw---	[	anon	]
00007f7ee087f000	208	00007f7ee087f000	208	208	rw---	[	anon	]
00007f79f0cad000	204	00007f79f0cad000	204	204	rw---	[	anon	]
00007f7b0425c000	204	00007f7b0425c000	204	204	rw---	[	anon	]
00007f7ba4c30000	204	00007f7ba4c30000	204	204	rw---	[	anon	]
00007f7dc8000000	204	00007f7dc8000000	4	4	rw---	[	anon	]
00007f79a1d85000	200	00007f79a1d85000	200	200	rw---	[	anon	]
00007f7b23a11000	200	00007f7b23a11000	200	200	rw---	[	anon	]
00007f7b6aa05000	200	00007f7b6aa05000	200	200	rw---	[	anon	]
00007f7c6cfe2000	200	00007f7c6cfe2000	0	0	rw---	[	anon	]
00007f7cbf692000	200	00007f7cbf692000	0	0	rw---	[	anon	]
00007f7ee042c000	200	00007f7ee042c000	200	200	rw---	[	anon	]
00007f7f32609000	200	00007f7f32609000	16	0	r-x--	libidn.so.11.6.1		
00007f7dc8ab4000	196	00007f7dc8ab4000	0	0	rw---	[	anon	]
00007f7e107a5000	196	00007f7e107a5000	0	0	rw---	[	anon	]
00007f7ca11c6000	192	00007f7ca11c6000	24	24	rw---	[	anon	]
00007f7ba0630000	188	00007f7ba0630000	188	188	rw---	[	anon	]
00007f7dc8794000	184	00007f7dc8794000	0	0	rw---	[	anon	]
00007f7f30cfa000	184	00007f7f30cfa000	0	0	rw---	[	anon	]
00007f7b1ff81000	180	00007f7b1ff81000	180	180	rw---	[	anon	]
00007f7b5773c000	180	00007f7b5773c000	180	180	rw---	[	anon	]
00007f7b6dbd4000	180	00007f7b6dbd4000	180	180	rw---	[	anon	]
00007f7a55024000	172	00007f7a55024000	172	172	rw---	[	anon	]
00007f7e39c4d000	172	00007f7e39c4d000	0	0	rw---	[	anon	]
00007f7ef0bdd000	172	00007f7ef0bdd000	172	172	rw---	[	anon	]
00007f79cd2f8000	168	00007f79cd2f8000	168	168	rw---	[	anon	]
00007f7e049c2000	168	00007f7e049c2000	0	0	rw---	[	anon	]
00007f7db3ace000	164	00007f7db3ace000	0	0	rw---	[	anon	]
00007f7ee4724000	164	00007f7ee4724000	164	164	rw---	[	anon	]
00007f7f084b3000	164	00007f7f084b3000	164	164	rw---	[	anon	]
00007f7f31f38000	164	00007f7f31f38000	44	0	r-x--	libsmime3.so		
00007f7f343c0000	164	00007f7f343c0000	8	0	r-x--	libk5crypto.so.3.1		
00007f795e198000	160	00007f795e198000	160	160	rw---	[	anon	]
00007f7b4a26c000	160	00007f7b4a26c000	160	160	rw---	[	anon	]
00007f7f319c1000	160	00007f7f319c1000	56	0	r-x--	libnssutil3.so		
00007f795c76c000	156	00007f795c76c000	156	156	rw---	[	anon	]
00007f7b259e0000	156	00007f7b259e0000	156	156	rw---	[	anon	]
00007f7f31151000	156	00007f7f31151000	0	0	r-x--	libssh2.so.1.0.1		
00007f7a95c07000	152	00007f7a95c07000	152	152	rw---	[	anon	]
00007f79c0000000	148	00007f79c0000000	148	148	rw---	[	anon	]
00007f7bdc5b1000	144	00007f7bdc5b1000	0	0	rw---	[	anon	]
00007f7c373a1000	144	00007f7c373a1000	0	0	rw---	[	anon	]
00007f7c927d3000	144	00007f7c927d3000	0	0	rw---	[	anon	]
00007f7ef4000000	144	00007f7ef4000000	144	144	rw---	[	anon	]
00007f7ef8000000	144	00007f7ef8000000	144	144	rw---	[	anon	]
00007f7efc000000	144	00007f7efc000000	144	144	rw---	[	anon	]
00007f7f07269000	144	00007f7f07269000	64	64	rw---	[	anon	]
00007f789fe5d000	140	00007f789fe5d000	140	140	rw---	[	anon	]
00007f7a4f77f000	140	00007f7a4f77f000	140	140	rw---	[	anon	]
00007f7f04a67000	140	00007f7f04a67000	140	140	rw---	[	anon	]
00007f7f14000000	140	00007f7f14000000	4	4	rw---	[	anon	]
00007f7f18000000	140	00007f7f18000000	4	4	rw---	[	anon	]
00007f7f20000000	140	00007f7f20000000	4	4	rw---	[	anon	]
00007f7f24000000	140	00007f7f24000000	4	4	rw---	[	anon	]
00007f7f28000000	140	00007f7f28000000	36	36	rw---	[	anon	]
00007f79369d9000	136	00007f79369d9000	136	136	rw---	[	anon	]
00007f7c26a1e000	136	00007f7c26a1e000	0	0	rw---	[	anon	]
00007f7d10219000	136	00007f7d10219000	0	0	rw---	[	anon	]
00007f7ee9132000	136	00007f7ee9132000	136	136	rw---	[	anon	]
00007f7f2ffb0000	136	00007f7f2ffb0000	32	0	r-x--	libafsocket.so		
1863000	132	1863000	24	20	rw---	[	anon	]
00007f7d1fef5000	132	00007f7d1fef5000	0	0	rw---	[	anon	]
00007f7ec8000000	132	00007f7ec8000000	4	4	rw---	[	anon	]
00007f7ed4000000	132	00007f7ed4000000	4	4	rw---	[	anon	]
00007f7f0833c000	132	00007f7f0833c000	132	132	rw---	[	anon	]
00007f7f10651000	132	00007f7f10651000	132	132	rw---	[	anon	]
00007f7853674000	128	#N/A	128	128	rw---	[	anon	]
00007f7ba0790000	128	00007f7ba0790000	128	128	rw---	[	anon	]
00007f7c31e53000	128	00007f7c31e53000	0	0	rw---	[	anon	]
00007f7f36f60000	128	00007f7f36f60000	100	0	r-x--	ld-2.12.so		
00007f7c8f630000	124	00007f7c8f630000	0	0	rw---	[	anon	]
00007f7e97019000	120	00007f7e97019000	0	0	rw---	[	anon	]
00007f7ee8795000	120	00007f7ee8795000	120	120	rw---	[	anon	]
00007f7be869b000	116	00007f7be869b000	0	0	rw---	[	anon	]
00007f7beb358000	116	00007f7beb358000	36	36	rw---	[	anon	]
00007f7ee43ea000	116	00007f7ee43ea000	116	116	rw---	[	anon	]
00007f7f07fe3000	116	00007f7f07fe3000	4	4	rw---	[	anon	]
00007f7f33963000	116	00007f7f33963000	8	0	r-x--	libselinux.so.1		
00007f7f35b21000	116	00007f7f35b21000	36	0	r-x--	libpcre.so.1.2.8		
00007f7ee4684000	112	00007f7ee4684000	112	112	rw---	[	anon	]
00007f7b75112000	108	00007f7b75112000	108	108	rw---	[	anon	]
00007f7c96fce000	108	00007f7c96fce000	0	0	rw---	[	anon	]
00007f7ce1392000	108	00007f7ce1392000	0	0	rw---	[	anon	]
00007f7d4fda7000	108	00007f7d4fda7000	0	0	rw---	[	anon	]
00007f7f07a70000	108	00007f7f07a70000	0	0	rw---	[	anon	]
00007f7f2fd93000	108	00007f7f2fd93000	28	0	r-x--	libaffile.so		
00007f7f350d5000	108	00007f7f350d5000	0	0	r----	libcrypto.so.1.0.1e		
00007f7956206000	104	00007f7956206000	104	104	rw---	[	anon	]
00007f7b82493000	104	00007f7b82493000	104	104	rw---	[	anon	]
00007f7c04763000	104	00007f7c04763000	20	20	rw---	[	anon	]
00007f7f04b79000	104	00007f7f04b79000	104	104	rw---	[	anon	]
00007f7f1044d000	104	00007f7f1044d000	104	104	rw---	[	anon	]
00007f7f30d28000	100	00007f7f30d28000	48	0	r-x--	libsasl2.so.2.0.23		
00007f7a050f9000	96	00007f7a050f9000	96	96	rw---	[	anon	]
00007f7a29529000	96	00007f7a29529000	96	96	rw---	[	anon	]
00007f7a8189d000	96	00007f7a8189d000	96	96	rw---	[	anon	]
00007f7c6dfc2000	96	00007f7c6dfc2000	0	0	rw---	[	anon	]
00007f7ee46a0000	92	00007f7ee46a0000	92	92	rw---	[	anon	]
00007f7ee8460000	92	00007f7ee8460000	92	92	rw---	[	anon	]
00007f7f35700000	92	00007f7f35700000	72	0	r-x--	libpthread-2.12.so		
00007f79386ae000	88	00007f79386ae000	88	88	rw---	[	anon	]
00007f7964f6b000	88	00007f7964f6b000	88	88	rw---	[	anon	]
00007f7c816eb000	88	00007f7c816eb000	0	0	rw---	[	anon	]
00007f7dc865f000	88	00007f7dc865f000	0	0	rw---	[	anon	]
00007f7f10ab1000	88	00007f7f10ab1000	88	88	rw---	[	anon	]
00007f7f341a6000	88	00007f7f341a6000	56	0	r-x--	libresolv-2.12.so		
00007f7f36a6b000	88	00007f7f36a6b000	8	0	r-x--	libnsl-2.12.so		
00007f7967616000	84	00007f7967616000	84	84	rw---	[	anon	]
00007f7af6c41000	84	00007f7af6c41000	84	84	rw---	[	anon	]
00007f7be7e44000	84	00007f7be7e44000	0	0	rw---	[	anon	]
00007f7ee34ed000	84	00007f7ee34ed000	84	84	rw---	[	anon	]
00007f7f33f90000	84	00007f7f33f90000	8	0	r-x--	libz.so.1.2.3		
00007ffe3b7ab000	84	00007ffe3b7ab000	24	24	rw---	[	stack	]
00007f7a0206c000	80	00007f7a0206c000	80	80	rw---	[	anon	]
00007f7a88ea6000	80	00007f7a88ea6000	80	80	rw---	[	anon	]
00007f7b42ad8000	80	00007f7b42ad8000	80	80	rw---	[	anon	]
00007f7f304c5000	80	00007f7f304c5000	8	8	rw---	librdkafka.so.1		
00007f7a7d876000	76	00007f7a7d876000	76	76	rw---	[	anon	]
00007f7c26326000	76	00007f7c26326000	0	0	rw---	[	anon	]
00007f7d98dff000	76	00007f7d98dff000	0	0	rw---	[	anon	]
00007f7c099e9000	72	00007f7c099e9000	12	12	rw---	[	anon	]
00007f7c8ed02000	72	00007f7c8ed02000	0	0	rw---	[	anon	]
00007f7ee8a15000	72	00007f7ee8a15000	72	72	rw---	[	anon	]
00007f7f082a5000	72	00007f7f082a5000	72	72	rw---	[	anon	]
00007f78a55bd000	68	00007f78a55bd000	68	68	rw---	[	anon	]
00007f7aff27d000	68	00007f7aff27d000	68	68	rw---	[	anon	]
00007f7b28e14000	68	00007f7b28e14000	68	68	rw---	[	anon	]
00007f7eec3e0000	68	00007f7eec3e0000	68	68	rw---	[	anon	]
00007f7eeee66000	68	00007f7eeee66000	0	0	rw---	[	anon	]
00007f7f04378000	68	00007f7f04378000	68	68	rw---	[	anon	]
00007f7f04562000	68	00007f7f04562000	68	68	rw---	[	anon	]
00007f7f10750000	68	00007f7f10750000	68	68	rw---	[	anon	]
00007f7abf81b000	64	00007f7abf81b000	64	64	rw---	[	anon	]
00007f7ee44a1000	64	00007f7ee44a1000	64	64	rw---	[	anon	]
00007f7ee8a00000	64	00007f7ee8a00000	64	64	rw---	[	anon	]
00007f7eec7c3000	64	00007f7eec7c3000	64	64	rw---	[	anon	]
00007f7f08202000	64	00007f7f08202000	64	64	rw---	[	anon	]
00007f7f0b36c000	64	00007f7f0b36c000	0	0	rw---	[	anon	]
00007f7f32a90000	64	00007f7f32a90000	0	0	r-x--	libhttp.so		
00007f786dd6c000	60	#N/A	60	60	rw---	[	anon	]
00007f7b8f82a000	60	00007f7b8f82a000	60	60	rw---	[	anon	]
00007f7ee09f4000	60	00007f7ee09f4000	0	0	rw---	[	anon	]
00007f7f084dc000	60	00007f7f084dc000	60	60	rw---	[	anon	]
00007f7f0b7c0000	60	00007f7f0b7c0000	0	0	rw---	[	anon	]
00007f7f11dba000	60	00007f7f11dba000	60	60	rw---	[	anon	]
00007f7808533000	56	#N/A	56	56	rw---	[	anon	]
00007f7b45166000	56	00007f7b45166000	56	56	rw---	[	anon	]
00007f7c219cb000	56	00007f7c219cb000	0	0	rw---	[	anon	]
00007f7ee48d8000	56	00007f7ee48d8000	56	56	rw---	[	anon	]
00007f7f084eb000	56	00007f7f084eb000	56	56	rw---	[	anon	]
00007f7f1087a000	56	00007f7f1087a000	56	56	rw---	[	anon	]
00007f7f13056000	56	00007f7f13056000	28	28	rw---	[	anon	]
00007f7f136e4000	56	00007f7f136e4000	0	0	rw---	[	anon	]
00007f7f30f42000	56	00007f7f30f42000	16	0	r-x--	liblber-2.4.so.2.10.3		
00007f7f37167000	56	00007f7f37167000	28	28	rw---	[	anon	]
00007f7ca9849000	52	00007f7ca9849000	0	0	rw---	[	anon	]
00007f7ee49ee000	52	00007f7ee49ee000	52	52	rw---	[	anon	]
00007f7ee89a1000	52	00007f7ee89a1000	52	52	rw---	[	anon	]
00007f7eec70f000	52	00007f7eec70f000	52	52	rw---	[	anon	]
00007f7ef03fb000	52	00007f7ef03fb000	52	52	rw---	[	anon	]
00007f7ef20f0000	52	00007f7ef20f0000	0	0	rw---	[	anon	]
00007f7f304dd000	52	00007f7f304dd000	16	0	r-x--	libkafka.so		
00007f7f33133000	52	00007f7f33133000	0	0	r-x--	libjson-c.so.3.0.1		
00007f7f33755000	52	00007f7f33755000	32	0	r-x--	libnss_files-2.12.so		
00007f7e1840c000	48	00007f7e1840c000	0	0	rw---	[	anon	]
00007f7eec6c4000	48	00007f7eec6c4000	48	48	rw---	[	anon	]
00007f7eec840000	48	00007f7eec840000	48	48	rw---	[	anon	]
00007f7f2f776000	48	00007f7f2f776000	0	0	r-x--	libdigestmd5.so.2.0.23		
00007f7f350f0000	48	00007f7f350f0000	0	0	rw---	libcrypto.so.1.0.1e		
00007f7b48132000	44	00007f7b48132000	44	44	rw---	[	anon	]
00007f7d5a2f6000	44	00007f7d5a2f6000	0	0	rw---	[	anon	]
00007f7ee0292000	44	00007f7ee0292000	44	44	rw---	[	anon	]
00007f7ee09e0000	44	00007f7ee09e0000	0	0	rw---	[	anon	]
00007f7ee326b000	44	00007f7ee326b000	0	0	rw---	[	anon	]
00007f7ee6c03000	44	00007f7ee6c03000	0	0	rw---	[	anon	]
00007f7eec724000	44	00007f7eec724000	44	44	rw---	[	anon	]
00007f7ef2ed9000	44	00007f7ef2ed9000	0	0	rw---	[	anon	]
00007f7f0ac1c000	44	00007f7f0ac1c000	0	0	rw---	[	anon	]
00007f7f32f26000	44	00007f7f32f26000	0	0	r-x--	libbasicfuncs.so		
00007f7f33341000	44	00007f7f33341000	0	0	r-x--	libjson-plugin.so		
00007f785a963000	40	#N/A	40	40	rw---	[	anon	]
00007f79ea6ff000	40	00007f79ea6ff000	40	40	rw---	[	anon	]
00007f7a317d8000	40	00007f7a317d8000	40	40	rw---	[	anon	]
00007f7a53cee000	40	00007f7a53cee000	40	40	rw---	[	anon	]
00007f7a91226000	40	00007f7a91226000	40	40	rw---	[	anon	]
00007f7a971ea000	40	00007f7a971ea000	40	40	rw---	[	anon	]
00007f7b27bf1000	40	00007f7b27bf1000	40	40	rw---	[	anon	]
00007f7b367e7000	40	00007f7b367e7000	40	40	rw---	[	anon	]
00007f7b5a249000	40	00007f7b5a249000	40	40	rw---	[	anon	]
00007f7ee713b000	40	00007f7ee713b000	0	0	rw---	[	anon	]
00007f7f12f36000	40	00007f7f12f36000	0	0	rw---	[	anon	]
00007f7f2fb88000	40	00007f7f2fb88000	16	0	r-x--	libsyslogformat.so		
00007f7f33d85000	40	00007f7f33d85000	8	0	r-x--	libkrb5support.so.0.1		
00007f7f34acb000	40	00007f7f34acb000	0	0	r----	libkrb5.so.3.3		
00007f7f36f55000	40	00007f7f36f55000	32	32	rw---	libsyslog-ng-3.23.so.0.0.0		
00007f79afe4d000	36	00007f79afe4d000	36	36	rw---	[	anon	]
00007f7da7965000	36	00007f7da7965000	0	0	rw---	[	anon	]
00007f7ee09eb000	36	00007f7ee09eb000	0	0	rw---	[	anon	]
00007f7ee471b000	36	00007f7ee471b000	36	36	rw---	[	anon	]
00007f7ee48ea000	36	00007f7ee48ea000	36	36	rw---	[	anon	]
00007f7ee746c000	36	00007f7ee746c000	36	36	rw---	[	anon	]
00007f7f10bcd000	36	00007f7f10bcd000	36	36	rw---	[	anon	]
00007f7a0be81000	32	00007f7a0be81000	32	32	rw---	[	anon	]
00007f7ac9e5e000	32	00007f7ac9e5e000	32	32	rw---	[	anon	]
00007f7dbb96b000	32	00007f7dbb96b000	0	0	rw---	[	anon	]
00007f7ee0e16000	32	00007f7ee0e16000	0	0	rw---	[	anon	]
00007f7eec71c000	32	00007f7eec71c000	32	32	rw---	[	anon	]
00007f7f0b06e000	32	00007f7f0b06e000	0	0	rw---	[	anon	]
00007f7f3354c000	32	00007f7f3354c000	0	0	r-x--	libappmodel.so		
00007f79a0fef000	28	00007f79a0fef000	28	28	rw---	[	anon	]
00007f79fc9d7000	28	00007f79fc9d7000	28	28	rw---	[	anon	]
00007f7a8ff54000	28	00007f7a8ff54000	28	28	rw---	[	anon	]
00007f7b065ec000	28	00007f7b065ec000	28	28	rw---	[	anon	]
00007f7edc529000	28	00007f7edc529000	0	0	rw---	[	anon	]
00007f7ee474d000	28	00007f7ee474d000	28	28	rw---	[	anon	]
00007f7ee8849000	28	00007f7ee8849000	28	28	rw---	[	anon	]
00007f7ee899a000	28	00007f7ee899a000	28	28	rw---	[	anon	]
00007f7eeb440000	28	00007f7eeb440000	0	0	rw---	[	anon	]
00007f7f30af1000	28	00007f7f30af1000	8	0	r-x--	libcrypt-2.12.so		
00007f7f31be8000	28	00007f7f31be8000	0	0	r----	libnssutil3.so		
00007f7f31f2d000	28	00007f7f31f2d000	0	0	r----	libnss3.so		
00007f7f3645c000	28	00007f7f3645c000	12	0	r-x--	librt-2.12.so		
00007f7f37178000	28	00007f7f37178000	20	0	r--s-	gconv-modules.cache		
00007f7b4f0c4000	24	00007f7b4f0c4000	24	24	rw---	[	anon	]
00007f7d58f0f000	24	00007f7d58f0f000	0	0	rw---	[	anon	]
00007f7dc89de000	24	00007f7dc89de000	0	0	rw---	[	anon	]
00007f7ee47c3000	24	00007f7ee47c3000	24	24	rw---	[	anon	]
00007f7ef08ed000	24	00007f7ef08ed000	24	24	rw---	[	anon	]
00007f7f07b75000	24	00007f7f07b75000	0	0	rw---	[	anon	]
00007f7f0ba4f000	24	00007f7f0ba4f000	0	0	rw---	[	anon	]
00007f7f13855000	24	00007f7f13855000	0	0	rw---	[	anon	]
00007f7f35366000	24	00007f7f35366000	0	0	rw---	libssl.so.1.0.1e		
00007f78d94d6000	20	00007f78d94d6000	20	20	rw---	[	anon	]
00007f798bf91000	20	00007f798bf91000	20	20	rw---	[	anon	]
00007f7cbce2c000	20	00007f7cbce2c000	0	0	rw---	[	anon	]
00007f7d9ab93000	20	00007f7d9ab93000	0	0	rw---	[	anon	]
00007f7ee0bbb000	20	00007f7ee0bbb000	20	20	rw---	[	anon	]
00007f7ee0cda000	20	00007f7ee0cda000	20	20	rw---	[	anon	]
00007f7ee8a10000	20	00007f7ee8a10000	20	20	rw---	[	anon	]
00007f7eeb72c000	20	00007f7eeb72c000	0	0	rw---	[	anon	]
00007f7ef098b000	20	00007f7ef098b000	20	20	rw---	[	anon	]
00007f7f04ea7000	20	00007f7f04ea7000	20	20	rw---	[	anon	]
00007f7f07264000	20	00007f7f07264000	4	4	rw---	[	anon	]
00007f7f08844000	20	00007f7f08844000	20	20	rw---	[	anon	]
00007f7f2c1e1000	20	00007f7f2c1e1000	20	0	r-x--	libnss_dns-2.12.so		
00007f7f2f364000	20	00007f7f2f364000	0	0	rw---	libdb-4.7.so		
00007f7f2f36a000	20	00007f7f2f36a000	0	0	r-x--	libsasldb.so.2.0.23		
00007f7a90ad2000	16	00007f7a90ad2000	16	16	rw---	[	anon	]
00007f7bc0ad7000	16	00007f7bc0ad7000	4	4	rw---	[	anon	]
00007f7cb28f0000	16	00007f7cb28f0000	0	0	rw---	[	anon	]
00007f7d605e7000	16	00007f7d605e7000	0	0	rw---	[	anon	]
00007f7de821b000	16	00007f7de821b000	0	0	rw---	[	anon	]
00007f7edc29b000	16	00007f7edc29b000	0	0	rw---	[	anon	]
00007f7ee08b3000	16	00007f7ee08b3000	16	16	rw---	[	anon	]
00007f7ee4895000	16	00007f7ee4895000	16	16	rw---	[	anon	]
00007f7ee48e6000	16	00007f7ee48e6000	16	16	rw---	[	anon	]
00007f7ee6b00000	16	00007f7ee6b00000	0	0	rw---	[	anon	]
00007f7f0432f000	16	00007f7f0432f000	16	16	rw---	[	anon	]
00007f7f2ebeb000	16	00007f7f2ebeb000	4	0	r-x--	libanonymous.so.2.0.23		
00007f7f2edf0000	16	00007f7f2edf0000	4	0	r-x--	libplain.so.2.0.23		
00007f7f2f570000	16	00007f7f2f570000	4	0	r-x--	libcrammd5.so.2.0.23		
00007f7f2f983000	16	00007f7f2f983000	4	0	r-x--	liblogin.so.2.0.23		
00007f7f304d9000	16	00007f7f304d9000	12	12	rw---	[	anon	]
00007f7f315b8000	16	00007f7f315b8000	12	0	r-x--	libplc4.so		
00007f7f32160000	16	00007f7f32160000	4	0	r----	libsmime3.so		
00007f7f323b2000	16	00007f7f323b2000	0	0	r----	libssl3.so		
00007f7f350fc000	16	00007f7f350fc000	0	0	rw---	[	anon	]
00007f7f35362000	16	00007f7f35362000	0	0	r----	libssl.so.1.0.1e		
00007f7f356f6000	16	00007f7f356f6000	16	16	r----	libc-2.12.so		
00007f7f356fc000	16	00007f7f356fc000	8	8	rw---	[	anon	]
00007f7f35919000	16	00007f7f35919000	4	4	rw---	[	anon	]
00007f7f36664000	16	00007f7f36664000	12	0	r-x--	libgthread-2.0.so.0.2800.8		
00007f7f37163000	16	00007f7f37163000	0	0	rw-s-	syslog-ng-pleistocene110.persist		
400000	12	400000	0	0	r-x--	syslog-ng		
00007f7a0e923000	12	00007f7a0e923000	12	12	rw---	[	anon	]
00007f7b363ad000	12	00007f7b363ad000	12	12	rw---	[	anon	]
00007f7bea959000	12	00007f7bea959000	0	0	rw---	[	anon	]
00007f7c10c96000	12	00007f7c10c96000	4	4	rw---	[	anon	]
00007f7c5eb4f000	12	00007f7c5eb4f000	0	0	rw---	[	anon	]
00007f7c78ffb000	12	00007f7c78ffb000	0	0	rw---	[	anon	]
00007f7f301d1000	12	00007f7f301d1000	4	4	rw---	libafsocket.so		
00007f7f317bd000	12	00007f7f317bd000	8	0	r-x--	libplds4.so		
00007f7f32a8d000	12	00007f7f32a8d000	0	0	rw---	libcurl.so.4.1.1		
00007f7f345ec000	12	00007f7f345ec000	4	0	r-x--	libcom_err.so.2.1		
00007f7f35d3e000	12	00007f7f35d3e000	8	0	r-x--	libsecret-storage.so.0.0.0		
00007f7f35f41000	12	00007f7f35f41000	12	0	r-x--	libevtlog-3.23.so.0.0.0		
00007f7f36868000	12	00007f7f36868000	8	0	r-x--	libgmodule-2.0.so.0.2800.8		
00007f79cb0d0000	8	00007f79cb0d0000	8	8	rw---	[	anon	]
00007f7a1e15b000	8	00007f7a1e15b000	8	8	rw---	[	anon	]
00007f7ee087d000	8	00007f7ee087d000	8	8	rw---	[	anon	]
00007f7ee7661000	8	00007f7ee7661000	0	0	rw---	[	anon	]
00007f7ef00af000	8	00007f7ef00af000	8	8	rw---	[	anon	]
00007f7f08694000	8	00007f7f08694000	8	8	rw---	[	anon	]
00007f7f2ffad000	8	00007f7f2ffad000	8	8	rw---	libaffile.so		
00007f7f301d4000	8	00007f7f301d4000	4	4	rw---	[	anon	]
00007f7f306ec000	8	00007f7f306ec000	0	0	r-x--	libconfgen.so		
00007f7f308ee000	8	00007f7f308ee000	0	0	r-x--	libfreebl3.so		
00007f7f31377000	8	00007f7f31377000	0	0	rw---	libssh2.so.1.0.1		
00007f7f315b2000	8	00007f7f315b2000	0	0	r----	libnspr4.so		
00007f7f315b4000	8	00007f7f315b4000	0	0	rw---	libnspr4.so		
00007f7f315b6000	8	00007f7f315b6000	0	0	rw---	[	anon	]
00007f7f31f34000	8	00007f7f31f34000	0	0	rw---	libnss3.so		
00007f7f31f36000	8	00007f7f31f36000	0	0	rw---	[	anon	]
00007f7f32605000	8	00007f7f32605000	0	0	r----	libldap-2.4.so.2.10.3		
00007f7f32607000	8	00007f7f32607000	0	0	rw---	libldap-2.4.so.2.10.3		
00007f7f32ca0000	8	00007f7f32ca0000	0	0	rw---	libhttp.so		
00007f7f33131000	8	00007f7f33131000	0	0	rw---	libbasicfuncs.so		
00007f7f33b82000	8	00007f7f33b82000	4	0	r-x--	libkeyutils.so.1.3		
00007f7f343be000	8	00007f7f343be000	4	4	rw---	[	anon	]
00007f7f34ad5000	8	00007f7f34ad5000	0	0	rw---	libkrb5.so.3.3		
00007f7f34d19000	8	00007f7f34d19000	0	0	rw---	libgssapi_krb5.so.2.2		
00007f7f356fa000	8	00007f7f356fa000	8	8	rw---	libc-2.12.so		
00007f7f3591d000	8	00007f7f3591d000	8	0	r-x--	libdl-2.12.so		
00007f7f36c82000	8	00007f7f36c82000	0	0	rw---	[	anon	]
602000	4	602000	4	4	rw---	syslog-ng		
00007f796742b000	4	00007f796742b000	4	4	rw---	[	anon	]
00007f79af13e000	4	00007f79af13e000	4	4	rw---	[	anon	]
00007f7a19224000	4	00007f7a19224000	4	4	rw---	[	anon	]
00007f7bdf492000	4	00007f7bdf492000	0	0	rw---	[	anon	]
00007f7befaec000	4	00007f7befaec000	0	0	rw---	[	anon	]
00007f7c1d0b6000	4	00007f7c1d0b6000	0	0	rw---	[	anon	]
00007f7c551e2000	4	00007f7c551e2000	0	0	rw---	[	anon	]
00007f7cac1aa000	4	00007f7cac1aa000	0	0	rw---	[	anon	]
00007f7d6bb06000	4	00007f7d6bb06000	0	0	rw---	[	anon	]
00007f7edc38e000	4	00007f7edc38e000	0	0	rw---	[	anon	]
00007f7ee0fdf000	4	00007f7ee0fdf000	4	4	rw---	[	anon	]
00007f7ee4ba3000	4	00007f7ee4ba3000	4	4	rw---	[	anon	]
00007f7ee8269000	4	00007f7ee8269000	4	4	rw---	[	anon	]
00007f7f003fa000	4	00007f7f003fa000	0	0	-----	[	anon	]
00007f7f00dfb000	4	00007f7f00dfb000	0	0	-----	[	anon	]
00007f7f017fc000	4	00007f7f017fc000	0	0	-----	[	anon	]
00007f7f021fd000	4	00007f7f021fd000	0	0	-----	[	anon	]
00007f7f02bfe000	4	00007f7f02bfe000	0	0	-----	[	anon	]
00007f7f035ff000	4	00007f7f035ff000	0	0	-----	[	anon	]
00007f7f1c3fa000	4	00007f7f1c3fa000	0	0	-----	[	anon	]
00007f7f1cdfb000	4	00007f7f1cdfb000	0	0	-----	[	anon	]
00007f7f1d7fc000	4	00007f7f1d7fc000	0	0	-----	[	anon	]
00007f7f1e1fd000	4	00007f7f1e1fd000	0	0	-----	[	anon	]
00007f7f1ebfe000	4	00007f7f1ebfe000	0	0	-----	[	anon	]
00007f7f1f5ff000	4	00007f7f1f5ff000	0	0	-----	[	anon	]
00007f7f2c3e5000	4	00007f7f2c3e5000	4	4	r----	libnss_dns-2.12.so		
00007f7f2c3e6000	4	00007f7f2c3e6000	4	0	rw---	libnss_dns-2.12.so		
00007f7f2c3e7000	4	00007f7f2c3e7000	0	0	-----	[	anon	]
00007f7f2cde8000	4	00007f7f2cde8000	0	0	-----	[	anon	]
00007f7f2d7e9000	4	00007f7f2d7e9000	0	0	-----	[	anon	]
00007f7f2e1ea000	4	00007f7f2e1ea000	0	0	-----	[	anon	]
00007f7f2edee000	4	00007f7f2edee000	0	0	r----	libanonymous.so.2.0.23		
00007f7f2edef000	4	00007f7f2edef000	0	0	rw---	libanonymous.so.2.0.23		
00007f7f2eff3000	4	00007f7f2eff3000	0	0	r----	libplain.so.2.0.23		
00007f7f2eff4000	4	00007f7f2eff4000	0	0	rw---	libplain.so.2.0.23		
00007f7f2f369000	4	00007f7f2f369000	0	0	rw---	[	anon	]
00007f7f2f56e000	4	00007f7f2f56e000	0	0	r----	libsasldb.so.2.0.23		
00007f7f2f56f000	4	00007f7f2f56f000	0	0	rw---	libsasldb.so.2.0.23		
00007f7f2f774000	4	00007f7f2f774000	0	0	r----	libcrammd5.so.2.0.23		
00007f7f2f775000	4	00007f7f2f775000	0	0	rw---	libcrammd5.so.2.0.23		
00007f7f2f981000	4	00007f7f2f981000	0	0	r----	libdigestmd5.so.2.0.23		
00007f7f2f982000	4	00007f7f2f982000	0	0	rw---	libdigestmd5.so.2.0.23		
00007f7f2fb86000	4	00007f7f2fb86000	0	0	r----	liblogin.so.2.0.23		
00007f7f2fb87000	4	00007f7f2fb87000	0	0	rw---	liblogin.so.2.0.23		
00007f7f2fd92000	4	00007f7f2fd92000	4	4	rw---	libsyslogformat.so		
00007f7f2ffaf000	4	00007f7f2ffaf000	4	4	rw---	[	anon	]
00007f7f306ea000	4	00007f7f306ea000	4	4	rw---	libkafka.so		
00007f7f306eb000	4	00007f7f306eb000	0	0	rw---	[	anon	]
00007f7f308ed000	4	00007f7f308ed000	0	0	rw---	libconfgen.so		
00007f7f30aef000	4	00007f7f30aef000	0	0	r----	libfreebl3.so		
00007f7f30af0000	4	00007f7f30af0000	0	0	rw---	libfreebl3.so		
00007f7f30cf8000	4	00007f7f30cf8000	0	0	r----	libcrypt-2.12.so		
00007f7f30cf9000	4	00007f7f30cf9000	0	0	rw---	libcrypt-2.12.so		
00007f7f30f40000	4	00007f7f30f40000	0	0	r----	libsasl2.so.2.0.23		
00007f7f30f41000	4	00007f7f30f41000	0	0	rw---	libsasl2.so.2.0.23		
00007f7f3114f000	4	00007f7f3114f000	0	0	r----	liblber-2.4.so.2.10.3		
00007f7f31150000	4	00007f7f31150000	0	0	rw---	liblber-2.4.so.2.10.3		
00007f7f317bb000	4	00007f7f317bb000	0	0	r----	libplc4.so		
00007f7f317bc000	4	00007f7f317bc000	0	0	rw---	libplc4.so		
00007f7f319bf000	4	00007f7f319bf000	0	0	r----	libplds4.so		
00007f7f319c0000	4	00007f7f319c0000	0	0	rw---	libplds4.so		
00007f7f31bef000	4	00007f7f31bef000	0	0	rw---	libnssutil3.so		
00007f7f32164000	4	00007f7f32164000	0	0	rw---	libsmime3.so		
00007f7f323b6000	4	00007f7f323b6000	0	0	rw---	libssl3.so		
00007f7f323b7000	4	00007f7f323b7000	0	0	rw---	[	anon	]
00007f7f3283a000	4	00007f7f3283a000	0	0	rw---	libidn.so.11.6.1		
00007f7f32f24000	4	00007f7f32f24000	0	0	r----	libm-2.12.so		
00007f7f32f25000	4	00007f7f32f25000	0	0	rw---	libm-2.12.so		
00007f7f33340000	4	00007f7f33340000	0	0	rw---	libjson-c.so.3.0.1		
00007f7f3354b000	4	00007f7f3354b000	0	0	rw---	libjson-plugin.so		
00007f7f33754000	4	00007f7f33754000	0	0	rw---	libappmodel.so		
00007f7f33961000	4	00007f7f33961000	0	0	r----	libnss_files-2.12.so		
00007f7f33962000	4	00007f7f33962000	0	0	rw---	libnss_files-2.12.so		
00007f7f33b7f000	4	00007f7f33b7f000	0	0	r----	libselinux.so.1		
00007f7f33b80000	4	00007f7f33b80000	0	0	rw---	libselinux.so.1		
00007f7f33b81000	4	00007f7f33b81000	0	0	rw---	[	anon	]
00007f7f33d83000	4	00007f7f33d83000	0	0	r----	libkeyutils.so.1.3		
00007f7f33d84000	4	00007f7f33d84000	0	0	rw---	libkeyutils.so.1.3		
00007f7f33f8e000	4	00007f7f33f8e000	0	0	r----	libkrb5support.so.0.1		
00007f7f33f8f000	4	00007f7f33f8f000	0	0	rw---	libkrb5support.so.0.1		
00007f7f341a4000	4	00007f7f341a4000	0	0	r----	libz.so.1.2.3		
00007f7f341a5000	4	00007f7f341a5000	0	0	rw---	libz.so.1.2.3		
00007f7f343bc000	4	00007f7f343bc000	0	0	r----	libresolv-2.12.so		
00007f7f343bd000	4	00007f7f343bd000	0	0	rw---	libresolv-2.12.so		
00007f7f345e9000	4	00007f7f345e9000	0	0	r----	libk5crypto.so.3.1		
00007f7f345ea000	4	00007f7f345ea000	0	0	rw---	libk5crypto.so.3.1		
00007f7f345eb000	4	00007f7f345eb000	0	0	rw---	[	anon	]
00007f7f347ee000	4	00007f7f347ee000	0	0	r----	libcom_err.so.2.1		
00007f7f347ef000	4	00007f7f347ef000	0	0	rw---	libcom_err.so.2.1		
00007f7f34d18000	4	00007f7f34d18000	0	0	r----	libgssapi_krb5.so.2.2		
00007f7f35917000	4	00007f7f35917000	4	4	r----	libpthread-2.12.so		
00007f7f35918000	4	00007f7f35918000	4	4	rw---	libpthread-2.12.so		
00007f7f35b1f000	4	00007f7f35b1f000	0	0	r----	libdl-2.12.so		
00007f7f35b20000	4	00007f7f35b20000	0	0	rw---	libdl-2.12.so		
00007f7f35d3d000	4	00007f7f35d3d000	4	4	rw---	libpcre.so.1.2.8		
00007f7f35f40000	4	00007f7f35f40000	4	4	rw---	libsecret-storage.so.0.0.0		
00007f7f36144000	4	00007f7f36144000	4	4	rw---	libevtlog-3.23.so.0.0.0		
00007f7f3645a000	4	00007f7f3645a000	4	4	rw---	libglib-2.0.so.0.2800.8		
00007f7f3645b000	4	00007f7f3645b000	4	4	rw---	[	anon	]
00007f7f36662000	4	00007f7f36662000	4	4	r----	librt-2.12.so		
00007f7f36663000	4	00007f7f36663000	0	0	rw---	librt-2.12.so		
00007f7f36867000	4	00007f7f36867000	4	4	rw---	libgthread-2.0.so.0.2800.8		
00007f7f36a6a000	4	00007f7f36a6a000	0	0	rw---	libgmodule-2.0.so.0.2800.8		
00007f7f36c80000	4	00007f7f36c80000	0	0	r----	libnsl-2.12.so		
00007f7f36c81000	4	00007f7f36c81000	0	0	rw---	libnsl-2.12.so		
00007f7f36f5f000	4	00007f7f36f5f000	4	4	rw---	[	anon	]
00007f7f37062000	4	00007f7f37062000	0	0	-----	[	anon	]
00007f7f3717f000	4	00007f7f3717f000	4	4	rw---	[	anon	]
00007f7f37180000	4	00007f7f37180000	4	4	r----	ld-2.12.so		
00007f7f37181000	4	00007f7f37181000	4	4	rw---	ld-2.12.so		
00007f7f37182000	4	00007f7f37182000	0	0	rw---	[	anon	]
00007ffe3b7e5000	4	00007ffe3b7e5000	4	0	r-x--	[	anon	]
ffffffffff600000	4	ffffffffff600000	0	0	r-x--	[	anon	]
								
----------------  ------  ------  ------
total kB        29939612 18249092 18246044

```

## Configuration

```
@version: 3.23
@define syslog_log_root_path "/logs/syslog-ng"
@define naming_scheme "${YEAR}_${MONTH}_${DAY}.log"
@include "/logs/lvapp/etc/syslog-ng/filters.conf"

@include "scl.conf"
@define kafka-implementation kafka-c


destination d_kafka{
      kafka(
                        bootstrap-servers("192.168.0.1:9092,192.168.0.2:9092,192.168.0.3:9092")
                        topic("syslogng")
                        config(
                                "sasl.username" => "myuser"
                                "sasl.password" => "mypassword"
                                "request.required.acks" => 0
                                "sasl.mechanisms" => "PLAIN"
                                "security.protocol" => "sasl_plaintext"
                                "broker.version.fallback" => "0.10.0.1"
                                "compression.codec" => "snappy"
                                "queue.buffering.max.ms" => "5000"
                                "queue.buffering.max.messages" => "500000"
                                "debug" => "broker,metadata,feature,admin,consumer,cgrp,topic,fetch"
                        )
                        message("$ISODATE $FULLHOST $MSGHDR$MSG\n")
                        log-fifo-size(2000000)
      );
};


filter f_kafka {
        not (source("s_syslog_112"));
};

###############################
#   Catch all rules
###############################
# !! Catchall must come first in config, otherwise final flags could stop some messages from beeing logged
# This flag means that the source of the message is ignored, only the filters are taken into account when matching messages.
# A log statement using the catchall flag processes every message that arrives to any of the defined sources.
log { filter(f_kafka); destination(d_kafka); flags(catchall);};



options {
    # Specifies whether syslog-ng should accept the timestamp received from the sending application or client.
    # If disabled, the time of reception will be used instead. This option can be specified globally, and per-source as well.
    # The local setting of the source overrides the global option if available.
    keep-timestamp(no); # As there are equipments in different areas worldwide, we normalize the timestamp by taking received time as reference
    # Enable or disable hostname rewriting.
    #   If enabled (keep-hostname(yes)), syslog-ng OSE assumes that the incoming log message was sent by the host specified in the HOST field of the message.
    #   If disabled (keep-hostname(no)), syslog-ng OSE rewrites the HOST field of the message, either to the IP address (if the use-dns() parameter is set to no), or to the hostname (if the use-dns() parameter is set to yes and the IP address can be resolved to a hostname) of the host sending the message to syslog-ng OSE. For details on using name resolution in syslog-ng OSE, see Section 17.3, Using name resolution in syslog-ng.
    #   Note
    #       If the log message does not contain a hostname in its HOST field, syslog-ng OSE automatically adds a hostname to the message.
    keep-hostname(no); # Trust no one !
    # Enable or disable the chained hostname format.
    # If a client sends the log message directly to the syslog-ng OSE server, the chain-hostnames() option is enabled on the server, and the client sends a hostname in the message that is different from its DNS hostname (as resolved from DNS by the syslog-ng OSE server), then the server can append the resolved hostname to the hostname in the message (separated with a / character) when the message is written to the destination.
    chain-hostnames(yes);
    #   Description: Enable or disable DNS usage.
    # The syslog-ng OSE application blocks on DNS queries, so enabling DNS may lead to a Denial of Service attack.
    # This option can be specified globally, and per-source as well.
    # The local setting of the source overrides the global option if available.
    use-dns(yes);
    # Add Fully Qualified Domain Name instead of short hostname.
    use-fqdn(yes);
    #File with reverse dns entries populated by a cron script to reduce dns queries
    dns-cache-hosts(/logs/syslog-ng/hosts);
    # The syslog-ng application can resolve the hostnames of the clients and include them in the log messages.
    # However, the performance of syslog-ng is severely degraded if the domain name server is unaccessible or slow.
    # Therefore, it is not recommended to resolve hostnames in syslog-ng. If you must use name resolution from syslog-ng, consider the following:
        # Use DNS caching. Verify that the DNS cache is large enough to store all important hostnames. (By default, the syslog-ng DNS cache stores 1007 entries.)
        dns-cache-size(500000);
        dns-cache-expire(345600); # 4J
        dns-cache-expire-failed(345600); #4J
    # Disable multithreaded syslog-ng (version > 3.3)
    threaded(no);
    # Specifies how many lines are flushed to a destination at a time.
    # The syslog-ng OSE application waits for this number of lines to accumulate and sends them off in a single batch.
    # Increasing this number increases throughput as more messages are sent in a single batch, but also increases message latency.
    # To limit the latency, adjust the flush-timeout() option.
    # By default, syslog-ng OSE waits for 100 lines.
    # If the source sends a few messages, but less than 100 messages, syslog-ng OSE will not send the messages to the destination until the flush-timeout() time passes (which is 10 seconds by default).
    # If you stop or reload syslog-ng OSE or in case of network sources, the connection with the client is closed, syslog-ng OSE automatically sends the unsent messages to the destination.
    flush-lines(2000);
    flush-timeout(10000); # 10s
    # The period between two STATS messages in seconds. STATS are log messages sent by syslog-ng, containing statistics about dropped log messages.
    stats-freq(600);
    # Specifies the detail of statistics syslog-ng collects about the processed messages.
    #   Level 0 collects only statistics about the sources and destinations
    #   Level 1 contains details about the different connections and log files, but has a slight memory overhead
    #   Level 2 contains detailed statistics based on the hostname.
    #   Level 3 contains detailed statistics based on various message parameters like facility, severity, or tags.
    stats-level(2);
    create-dirs(yes);
    owner(syslogng);
    dir-owner(syslogng);
    group(syslogng);
    perm(0640);
    dir-perm(02751);
};




options {
    threaded(yes) ;
};

source s_syslog_110_udp5141{
network(ip(192.168.1.12) transport("udp") port(5141) so_rcvbuf(134217728) log-iw-size(50000) log_fetch_limit(2000) flags("threaded"));
};


source s_syslog_110_udp5142{
network(ip(192.168.1.12) transport("udp") port(5142) so_rcvbuf(134217728) log-iw-size(50000) log_fetch_limit(2000) flags("threaded"));
};


source s_syslog_110_udp5143{
network(ip(192.168.1.12) transport("udp") port(5143) so_rcvbuf(134217728) log-iw-size(50000) log_fetch_limit(2000) flags("threaded"));
};


source s_syslog_110_udp5144{
network(ip(192.168.1.12) transport("udp") port(5144) so_rcvbuf(134217728) log-iw-size(50000) log_fetch_limit(2000) flags("threaded"));
};



source s_syslog_110{
    network(ip(192.168.1.12) transport("udp") so_rcvbuf(134217728) log-iw-size(50000) log_fetch_limit(2000) flags("threaded"));
    network(ip(192.168.1.12) transport("tcp") port(5140) max-connections(10000) flags("threaded") log_fetch_limit(500));
    network(ip(192.168.1.12) transport("tcp") port(514) max-connections(10000) flags("threaded") log_fetch_limit(500) log-iw-size(1000000));
};



###############################
# Destinations 110
###############################

destination d_network_debug  {
    file("/logs/syslog-ng/network/debug/${YEAR}_${MONTH}_${DAY}.log" group("logs_network_debug") dir-group("logs_network_debug") log-fifo-size(2000000));
};

destination d_network_fw_misc  {
    file("/logs/syslog-ng/network/fw/misc/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log" group("logs_fw") dir-group("logs_fw") log-fifo-size(100000));
};

destination d_network_fw_ngfw  {
    file("/logs/syslog-ng/network/fw/ngfw/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log" group("logs_fw") dir-group("logs_fw") log-fifo-size(100000));
};

destination d_network_wifi  {
    file("/logs/syslog-ng/network/wifi/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log" group("logs_wifi") dir-group("logs_wifi") log-fifo-size(100000));
};

destination d_network_vpn  {
    file("/logs/syslog-ng/network/vpn/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log"  group("logs_vpn") dir-group("logs_vpn") log-fifo-size(100000));
};

destination d_network_relay  {
    file("/logs/syslog-ng/network/relay/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log"  group("logs_nwrelay") dir-group("logs_nwrelay") log-fifo-size(100000));
};

destination d_network_dhcp  {
    file("/logs/syslog-ng/network/dhcp/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log"  group("logs_dhcp") dir-group("logs_dhcp") log-fifo-size(100000));
};

destination d_network_8021x  {
    file("/logs/syslog-ng/network/8021x/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log"  group("logs_8021x") dir-group("logs_8021x") log-fifo-size(100000));
};

destination d_network_dns  {
    file("/logs/syslog-ng/network/dns/$FULLHOST/${YEAR}_${MONTH}_${DAY}.log"  group("logs_dns") dir-group("logs_dns") log-fifo-size(100000));
};


###############################
# Filtres 110
###############################

filter f_network_wifi {
    host(xxx.fqdn.fr) or
    host("ACSWIFI.*")
   ;
};

filter f_network_fw_ngfw {
    host(".*?ngfw.*") or
    host("panorama2.*");
};

filter f_network_dhcp {
     host(".*dhcp.*");
 };



filter f_debug {
   not filter(f_network_wifi) and
   not filter(f_network_dhcp) and
   not filter(f_network_fw_ngfw);
};


###############################
# Journalisation
###############################
log {
    source(s_syslog_110);
    source(s_syslog_110_udp5141);
    source(s_syslog_110_udp5142);
    source(s_syslog_110_udp5143);
    source(s_syslog_110_udp5144);
    # Every channel of the junction received a copy of the message, unless there is a final flag before
    # Final flags are applied only within the junction and not globally
    junction {
        channel {filter(f_debug); destination(d_network_debug);};
        channel {filter(f_network_wifi); destination(d_network_wifi); flags(final);};
        channel {filter(f_network_dhcp); destination(d_network_dhcp); flags(final);};
        channel {filter(f_network_fw_ngfw); destination(d_network_fw_ngfw); flags(final);};
        channel {destination(d_network_fw_misc); flags(final);};
    };
};



```

### PR DESCRIPTION
**Pull request by alltilla**
Fixes #2929

### CODE REVIEW

File: modules/kafka/kafka-dest-worker.c [hunk 1]
```diff
@@ -86,8 +82,8 @@ _publish_message(KafkaDestWorker *self, LogMessage *msg)
 
   /* we passed the allocated buffers to rdkafka, which will eventually free them */
   g_string_steal(message);
-  if (key->str)
-    g_string_steal(key);
+  /* key is not freed by rdkafka */
+  g_string_set_size(key, 0);
```
Comment (MrAnno) [inline modules/kafka/kafka-dest-worker.c]: `rd_kafka_produce()` copies the key for itself, I checked. :+1:

Comment (MrAnno) [reply modules/kafka/kafka-dest-worker.c]: Could you remove the comment, please? I think it's not worth mentioning the opposite.

**Comment by bazsi** [comment]
In that case we shouldn't need the set_size() call either. We would just
reuse the string buffer.

File: modules/kafka/kafka-dest-worker.c (hunk 1 above)
Comment (MrAnno) [reply modules/kafka/kafka-dest-worker.c]: `log_template_format()` truncates the string, you can actually remove this line. I'd also use `self->key` directly, removing the local key variable.

Comment (alltilla) [reply modules/kafka/kafka-dest-worker.c]: Done! :)

**Comment by alltilla** [comment]
Updated the `evt_tag_str("key", self->key->str ? : "NULL")` part.

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: modules/kafka/kafka-dest-worker.c [hunk 2]
```diff
@@ -54,18 +54,13 @@ static gboolean
...
-    .len = 0
-  });
   GString *message = self->message;
 
   if (rd_kafka_produce(owner->topic,
                        RD_KAFKA_PARTITION_UA,
                        RD_KAFKA_MSG_F_FREE | RD_KAFKA_MSG_F_BLOCK,
                        message->str, message->len,
-                       key->str, key->len,
+                       self->key->str, self->key->len,
```
Comment (bazsi) [inline modules/kafka/kafka-dest-worker.c]: Key being NULL might have a significance here

File: modules/kafka/kafka-dest-worker.c [hunk 3]
```diff
@@ -54,18 +54,13 @@ static gboolean
 _publish_message(KafkaDestWorker *self, LogMessage *msg)
 {
   KafkaDestDriver *owner = (KafkaDestDriver *) self->super.owner;
-  GString *key = self->key ? : &((GString)
-  {
-    .str = NULL,
-    .len = 0
-  });
   GString *message = self->message;
```
Comment (bazsi) [inline modules/kafka/kafka-dest-worker.c]: I would also drop this local variable

File: modules/kafka/kafka-dest-worker.c (hunk 2 above)
Comment (MrAnno) [reply modules/kafka/kafka-dest-worker.c]: They key is now always alloced with `g_string_sized_new(0);`.

Comment (bazsi) [reply modules/kafka/kafka-dest-worker.c]: But that would set str to a string with zero length, but key->str will never be NULL.

Comment (MrAnno) [reply modules/kafka/kafka-dest-worker.c]: Oh sorry, I misunderstood your comment.

Comment (alltilla) [reply modules/kafka/kafka-dest-worker.c]: You are right. It comes to this in the end:
```
	if (key) {
		rkm->rkm_key     = p;
		rkm->rkm_key_len = keylen;
		memcpy(rkm->rkm_key, key, keylen);
	} else {
		rkm->rkm_key = NULL;
		rkm->rkm_key_len = 0;
	}
```
I will fix it!

Comment (alltilla) [reply modules/kafka/kafka-dest-worker.c]: Changed it to `self->key->len ? self->key->str : NULL`

File: modules/kafka/kafka-dest-worker.c (hunk 3 above)
Comment (alltilla) [reply modules/kafka/kafka-dest-worker.c]: Done! Thanks :)

**Comment by alltilla** [comment]
@bazsi Thanks for the approve! :)
I thought about the empty key scenario, but we cannot give empty string due to the grammar block logic:
```
[09:27][ ~/Work/install/OSE ] $ ./sbin/syslog-ng -Fe
Error parsing kafka, syntax error, unexpected ')', expecting LL_IDENTIFIER or LL_STRING in block destination kafka() at /home/alltilla/Work/install/OSE/share/syslog-ng/include/scl/kafka/plugin.conf:48:4:67-4:68:
1       
2       #Start Block block destination kafka() at /home/alltilla/Work/install/OSE/share/syslog-ng/include/scl/kafka/plugin.conf:48
3       
4----->     kafka-c(bootstrap_servers("127.0.0.1:9092") topic("test") key() );
4----->                                                                   ^
5       
6       #End Block block destination kafka() at /home/alltilla/Work/install/OSE/share/syslog-ng/include/scl/kafka/plugin.conf:48
7       

Included from /home/alltilla/Work/install/OSE/etc/syslog-ng.conf:10:7-28:8:
5       
6       @include "scl.conf"
7       @define kafka-implementation kafka-c
8       
9       destination d_kafka{
10---->       kafka(
10---->       ^^^^^^^
11---->                         bootstrap-servers("127.0.0.1:9092")
12---->                         topic("test")
13---->                         key('')
14----> #                        config(
15----> #                                "sasl.username" => "myuser"

[09:27][ ~/Work/install/OSE ] $
[09:27][ ~/Work/install/OSE ] $
[09:27][ ~/Work/install/OSE ] $
[09:27][ ~/Work/install/OSE ] $ ./sbin/syslog-ng -Fe
Error parsing kafka, syntax error, unexpected ')', expecting LL_IDENTIFIER or LL_STRING in block destination kafka() at /home/alltilla/Work/install/OSE/share/syslog-ng/include/scl/kafka/plugin.conf:48:4:67-4:68:
1       
2       #Start Block block destination kafka() at /home/alltilla/Work/install/OSE/share/syslog-ng/include/scl/kafka/plugin.conf:48
3       
4----->     kafka-c(bootstrap_servers("127.0.0.1:9092") topic("test") key() );
4----->                                                                   ^
5       
6       #End Block block destination kafka() at /home/alltilla/Work/install/OSE/share/syslog-ng/include/scl/kafka/plugin.conf:48
7       

Included from /home/alltilla/Work/install/OSE/etc/syslog-ng.conf:10:7-28:8:
5       
6       @include "scl.conf"
7       @define kafka-implementation kafka-c
8       
9       destination d_kafka{
10---->       kafka(
10---->       ^^^^^^^
11---->                         bootstrap-servers("127.0.0.1:9092")
12---->                         topic("test")
13---->                         key("")
14----> #                        config(
15----> #                                "sasl.username" => "myuser"
```

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by bazsi** [comment]
The scl issue should be a separate one ane this merged independently, I think.

**Comment by kira-syslogng** [comment]
Build SUCCESS
