### PR TITLE
Fix threaded source tests

### LINKED ISSUE #3920: Race condition between AH_CONFIG_CHANGED and threaded sources
# syslog-ng
## Version of syslog-ng
current master (191c4fb5617c84fe420284fc993ba6b2ad907644)

## Platform
Linux

The threaded source and threaded fetcher unit tests started to crash occasionally.
I can't reproduce the issue in my environment, but this occurs in different GitHub Actions and GitLab CI  builds as well.
For example:
https://github.com/syslog-ng/syslog-ng/runs/5236319117

Fortunately, the core file was available:
```
Thread 3 (Thread 0x7fc6e3dd4640 (LWP 9661)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fc6e597475c in g_mutex_lock_slowpath (mutex=0x7fc6e5b34e30 <stats_mutex>) at ../../../glib/gthread-posix.c:1493
#2  0x00007fc6e5aa9edb in stats_lock () at ../lib/stats/stats-registry.c:58
#3  0x00007fc6e5abdbf1 in log_tags_get_by_name (name=0x4086d6 "citrom") at ../lib/logmsg/tags.c:91
#4  0x00007fc6e5ab3c4a in log_msg_set_tag_by_name (self=0x7fc6d4004350, name=0x4086d6 "citrom") at ../lib/logmsg/logmsg.c:899
#5  0x0000000000404af6 in create_empty_message () at ../libtest/cr_template.c:89
#6  0x0000000000404b96 in create_sample_message () at ../libtest/cr_template.c:107
#7  0x0000000000404037 in _run_simple (s=0x19cb4d0) at ../lib/logthrsource/tests/test_logthrsourcedrv.c:181
#8  0x00007fc6e5ac66a4 in log_threaded_source_worker_run (s=0x19cc940) at ../lib/logthrsource/logthrsourcedrv.c:169
#9  0x00007fc6e5a5f6bc in _worker_thread_func (st=0x19cc940) at ../lib/mainloop-threaded-worker.c:79
#10 0x00007fc6e594bf5d in g_thread_proxy (data=0x19ae760) at ../../../glib/gthread.c:827
#11 0x00007fc6e56edd80 in start_thread (arg=0x7fc6e3dd4640) at pthread_create.c:481
#12 0x00007fc6e5802bdf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fc6e4de8640 (LWP 9659)):
#0  0x00007fc6e5802f06 in epoll_wait (epfd=5, events=0x7fc6e5ba9790 <self+144>, maxevents=32, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0x00007fc6e5b66470 in nn_poller_wait () from /usr/lib/libcriterion.so.3
#2  0x00007fc6e5b5b4d4 in nn_worker_routine () from /usr/lib/libcriterion.so.3
#3  0x00007fc6e5b5dd36 in nn_thread_main_routine () from /usr/lib/libcriterion.so.3
#4  0x00007fc6e56edd80 in start_thread (arg=0x7fc6e4de8640) at pthread_create.c:481
#5  0x00007fc6e5802bdf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fc6e4e0ba80 (LWP 9658)):
#0  g_str_hash (v=0x21) at ../../../glib/ghash.c:2333
#1  0x00007fc6e5aa91a1 in stats_cluster_hash (self=0x7ffc6c2df0e0) at ../lib/stats/stats-cluster.c:210
#2  0x00007fc6e590e976 in g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x7ffc6c2df0e0, hash_table=0x19ae180 = {...}) at ../../../glib/ghash.c:472
#3  g_hash_table_lookup (hash_table=0x19ae180 = {...}, key=0x7ffc6c2df0e0) at ../../../glib/ghash.c:1511
#4  0x00007fc6e5aaa5f5 in stats_unregister_counter (sc_key=0x7ffc6c2df0e0, type=1, counter=0x19c5eb0) at ../lib/stats/stats-registry.c:304
#5  0x00007fc6e5abdeca in log_tags_reinit_stats () at ../lib/logmsg/tags.c:184
#6  0x00007fc6e5a3daf1 in run_application_hook (type=7) at ../lib/apphook.c:124
#7  0x00007fc6e5a3de0b in app_config_changed () at ../lib/apphook.c:260
#8  0x0000000000403e21 in start_test_threaded_source (s=0x19cb4d0) at ../lib/logthrsource/tests/test_logthrsourcedrv.c:131
#9  0x00000000004043fd in logthrsourcedrv_test_threaded_source_suspend_impl () at ../lib/logthrsource/tests/test_logthrsourcedrv.c:231
#10 0x00007fc6e5b41ec4 in criterion_internal_test_main () from /usr/lib/libcriterion.so.3
#11 0x00000000004043aa in logthrsourcedrv_test_threaded_source_suspend_jmp () at ../lib/logthrsource/tests/test_logthrsourcedrv.c:223
#12 0x00007fc6e5b4039b in run_test_child () from /usr/lib/libcriterion.so.3
#13 0x00007fc6e5b8d925 in bxfi_main () from /usr/lib/libcriterion.so.3
#14 0x00007fc6e572d7ed in __libc_start_main (main=0x7fc6e5b4d863 <main>, argc=1, argv=0x7ffc6c2df688, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc6c2df678) at ../csu/libc-start.c:332
#15 0x00000000004034ea in _start ()
```

### PR DESCRIPTION
**Pull request by MrAnno**
This fixes only the unit test failure described in #3920.

The PR won't stop the race from happening in production, I just removed the unnecessary `app_config_changed()` call from the unit test.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/logthrsource/tests/test_logthrfetcherdrv.c [hunk 1]
```diff
@@ -131,7 +131,6 @@ start_test_threaded_fetcher(TestThreadedFetcherDriver *s)
 {
   cr_assert(log_pipe_init(&s->super.super.super.super.super));
   cr_assert(log_pipe_on_config_inited(&s->super.super.super.super.super));
-  app_config_changed();
```
Comment (Barkodcz) [inline lib/logthrsource/tests/test_logthrfetcherdrv.c:134]: Optional:
just a question, shouldn't we check if everything is "alright" after the reinit?
Maybe already exist this kind of test, just I didn't find it.

File: lib/logmsg/tags.c [hunk 2]
```diff
@@ -170,6 +170,7 @@ log_tags_reinit_stats(void)
 {
```
Comment (Barkodcz) [inline lib/logmsg/tags.c:170]: Optional:
`log_tags_reinit_stats` can be static function? If I saw correctly this function is only called in this file. It's not important just to make sure this function can be called by application hook.

**Review by Barkodcz — APPROVED** [review]
LGTM!
Nice catch!

File: lib/logthrsource/tests/test_logthrfetcherdrv.c (hunk 1 above)
Comment (MrAnno) [reply lib/logthrsource/tests/test_logthrfetcherdrv.c:134]: I don't understand this question.

File: lib/logmsg/tags.c (hunk 2 above)
Comment (MrAnno) [reply lib/logmsg/tags.c:170]: It could be static. Currently, it is only used by an app hook.

**Review by bazsi — APPROVED** [review]

File: lib/logthrsource/tests/test_logthrfetcherdrv.c (hunk 1 above)
Comment (MrAnno) [reply lib/logthrsource/tests/test_logthrfetcherdrv.c:134]: Do you mean that we should write a test case where a config reinit with `AH_CONFIG_CHANGED` is tested with threaded sources/destinations?

That would be a really useful test, which could validate a potential bugfix for #3920.

Comment (Barkodcz) [reply lib/logthrsource/tests/test_logthrfetcherdrv.c:134]: Sorry for the long wait, I didn't notice the comment :'(

Yes. Config reinit is the basic element of syslog-ng, but do a lot of stuff. My opinion is that could be good if we test it's everything run correctly after a config reinit.

I didn't know there is a related bug. I'm not sure it is possible to make a test case that can reproduce that bug every time (this is also my opinion :D - and please prove me wrong :) )

But one thing sure, I don't want to block this PR, I think that bug is could be in a new PR.

**Comment by MrAnno** [comment]
@gaborznagy Could you help with the merge of this PR, please? :)

**Review by gaborznagy — APPROVED** [review]
