### PR TITLE
disk-buffer: add metrics for abandoned disk-buffer files

### LINKED ISSUE #4400: another SLES 12 post build check fail
Yet another SLES 12 post build check fail.

```
[   73s] I: Program is using implicit definitions of special functions.
[   73s]    these functions need to use their correct prototypes to allow
[   73s]    the lightweight buffer overflow checking to work.
[   73s]      - Implicit memory/string functions need #include <string.h>.
[   73s]      - Implicit *printf functions need #include <stdio.h>.
[   73s]      - Implicit *printf functions need #include <stdio.h>.
[   73s]      - Implicit *read* functions need #include <unistd.h>.
[   73s]      - Implicit *recv* functions need #include <sys/socket.h>.
[   73s] E: syslog-ng implicit-fortify-decl lib/stats/stats-cluster-key-builder.c:157
```
The good news is, that both RHEL 7 and SLES 12 will be end of life in 2024 :-)

### PR DESCRIPTION
**Pull request by alltilla**
Availability is the same as the `disk_queue_dir_available_bytes` metric.

Example metrics:
```
syslogng_disk_queue_capacity_bytes{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 104853504
syslogng_disk_queue_disk_allocated_bytes{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 273408
syslogng_disk_queue_disk_usage_bytes{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 269312
syslogng_disk_queue_events{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 860
```

Depends on #4399 and #4356.

Signed-off-by: Attila Szakacs <attila.szakacs@axoflow.com>

Fixes #4400

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by alltilla** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

File: modules/diskq/diskq-global-metrics.c [hunk 1]
```diff
@@ -169,6 +173,66 @@ _init_abandoned_disk_buffer_sc_keys(StatsClusterKey *queued_sc_key, StatsCluster
...
+  options.read_only = TRUE;
+
+  LogQueue *queue;
+  if (reliable)
+    queue = log_queue_disk_reliable_new(&options, abs_filename, NULL, STATS_LEVEL0, NULL, NULL);
+  else
+    queue = log_queue_disk_non_reliable_new(&options, abs_filename, NULL, STATS_LEVEL0, NULL, NULL);
+  LogQueueDisk *queue_disk = (LogQueueDisk *) queue;
+
+  if (!log_queue_disk_start(queue))
```
Comment (MrAnno) [inline modules/diskq/diskq-global-metrics.c:197]: Questions:
I'm wondering how expensive this call can be.

Is it okay to enable this by default? If so, is it OK to repeat it every 5 minutes?
A dir might have thousands of abandoned disk-buffer files (or not-abandoned, or just regular files).

This feature implies that 2 syslog-ng instances can not use the same disk-buffer directory, otherwise they will report each others' buffers as abandoned.
I think this is good behavior, but considering the above, I think it is unnecessary to do periodic abandoned buffer checks, because no one will change those values between an acquire/release cycle.

TLDR: I think we should remove the periodic abandoned buffer metrics update from the timer callback, and call it only when a new directory is added by `acquire`. This would keep this potentially expensive call at startup time.
What about buffers that were abandoned during runtime? I think it's not possible unless they are corrupted, but we should not try to open corrupted buffer files in the main syslog-ng process. Reloading might abandon buffers, but that will be detected in `acquire`.

**Review by MrAnno — COMMENTED** [review]
Nice feature.

For the record: `diskq-global-metrics` considers buffers abandoned when they are not used in the currently running syslog-ng instance. This is a bit different than what we do in our persist file: we abandon buffers only when 2 consecutive syslog-ng restart does not acquire them.

I think this is not a real problem, I just wanted to mention it.

File: modules/diskq/logqueue-disk-non-reliable.c [hunk 2]
```diff
@@ -169,6 +170,7 @@ _move_messages_from_disk_to_qout(LogQueueDiskNonReliable *self)
       g_queue_push_tail(self->qout, msg);
       g_queue_push_tail(self->qout, LOG_PATH_OPTIONS_TO_POINTER(&path_options));
       log_queue_memory_usage_add(&self->super.super, log_msg_get_size(msg));
+      log_queue_disk_update_disk_related_counters(&self->super);
```
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/logqueue-disk-non-reliable.c:173]: Yes, It will when I rebase, sorry for that.

File: modules/diskq/diskq-global-metrics.c [hunk 3]
```diff
@@ -103,6 +105,32 @@ _update_dir_available_space_metrics(const gchar *dir)
   stats_unlock();
 }
 
+static gboolean
+_is_disk_buffer_file(const gchar *filename)
+{
+  const gsize min_len = sizeof("syslog-ng-00000.qf") - 1;
+  const gsize prefix_len = sizeof("syslog-ng-") - 1;
+  const gsize extension_start = sizeof("syslog-ng-00000") - 1;
```
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c:121]: It is just an optimization, to calculate these compile time. I can change it to strlen, would you like me to do so for the sake of readability?

File: modules/diskq/diskq-global-metrics.c (hunk 1 above)
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c:197]: I agree. The only case where this module does not get notified about a new disk-buffer file is corruption. The code currently tries to open the corrupted file and if it succeeds it creates metrics for it.
Two things:
  1. We can call the `diskq_global_metrics_file_released()` fn in the corrupted restart fn, so we don't need the poll at all.
  2. As you mentioned, we might not want to create metrics for the corrupted files. But I would ask you what is the reasoning behind it? I did not see a problem with it.

File: modules/diskq/diskq-global-metrics.c [hunk 4]
```diff
@@ -197,7 +197,63 @@ diskq_global_metrics_watch_dir(const gchar *dir)
...
+  gchar *filename = g_path_get_basename(abs_filename);
+
+  g_mutex_lock(&self->lock);
+  {
+    GHashTable *acquired_files = g_hash_table_lookup(self->dirs, dir);
+    if (!acquired_files)
+      {
+        g_mutex_unlock(&self->lock);
+        g_free(filename);
+        goto exit;
```
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/diskq-global-metrics.c:424]: If you don't want to force-watch, a `g_assert_not_reached()` might save us some future trouble.

File: modules/diskq/diskq-global-metrics.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/diskq-global-metrics.c:121]: No, I was just curious. Thanks.

File: modules/diskq/diskq-global-metrics.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c:424]: I started with that and the unit tests crashed on that, because they don't call watch, but call acquire_queue. I can add a watch to the unit tests, too, but it would seem strange IMO.

File: modules/diskq/diskq-global-metrics.c (hunk 1 above)
Comment (MrAnno) [reply modules/diskq/diskq-global-metrics.c:197]: I'm afraid a corrupted disk-buffer file may crash the syslog-ng instance. Also, corrupt files may have corrupt headers, therefore invalid entries.

I know... Every crash possibility should be fixed.
But if we could avoid doing all of this at runtime (moving them to startup time only), I think it would be much safer and cheaper. A metric, after all, should not affect performance or stability.

I'd vote for 2), but if you insist, 1) is good too.

File: modules/diskq/diskq-global-metrics.c [hunk 5]
```diff
@@ -105,6 +113,205 @@ _update_dir_metrics(gpointer key, gpointer value, gpointer user_data)
...
+    return FALSE;
+
+  for (gint i = prefix_len; i < extension_start; i++)
+    {
+      if (filename[i] < '0' || filename[i] > '9')
+        return FALSE;
+    }
+
+  if (strncmp(&filename[extension_start], ".qf", 3) != 0 && strncmp(&filename[extension_start], ".rqf", 4) != 0)
+    return FALSE;
```
Comment (MrAnno) [inline modules/diskq/diskq-global-metrics.c:137]: Sorry, another note because I did not notice:

I think we could be a bit stricter by not allowing any suffixes.
For example, if we don't want to check corrupt files, we should not allow a suffix, otherwise we should look for `corrupted`.

File: modules/diskq/diskq-global-metrics.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/diskq-global-metrics.c:424]: From a clean-code perspective, if the test does not call watch() but only calls acquire(), that's an invalid usage of the API and the test should probably catch that.

it's either we do a force-watch, or we don't allow calling this method without a previous watch() call. With the current code, calling `diskq_global_metrics_file_acquired()` without a previous watch() call will misfunction.

File: modules/diskq/diskq-global-metrics.c (hunk 5 above)
Comment (MrAnno) [reply modules/diskq/diskq-global-metrics.c:137]: Ahh, corrupted buffers are also numbered... Okay... It's not worth all the trouble.

File: modules/diskq/diskq-global-metrics.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c]: I agree, fixed.

File: modules/diskq/diskq-global-metrics.c [hunk 6]
```diff
@@ -103,6 +105,32 @@ _update_dir_available_space_metrics(const gchar *dir)
   stats_unlock();
 }
 
+static gboolean
+_is_disk_buffer_file(const gchar *filename)
```
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c]: Moved to `qdisk.c`.

File: modules/diskq/diskq-global-metrics.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c]: In the end I have changed it, as the new code would have been a lot more complicated.

File: modules/diskq/diskq-global-metrics.c [hunk 7]
```diff
@@ -103,6 +105,32 @@ _update_dir_available_space_metrics(const gchar *dir)
...
+  gsize len = strlen(filename);
+  if (len < min_len)
+    return FALSE;
+
+  if (strncmp(filename, "syslog-ng-", prefix_len) != 0)
+    return FALSE;
+
+  for (gint i = prefix_len; i < extension_start; i++)
+    {
+      if (filename[i] < '0' || filename[i] > '9')
```
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c]: Good idea, I changed it.

File: modules/diskq/diskq-global-metrics.c [hunk 8]
```diff
@@ -131,12 +132,93 @@ _is_disk_buffer_file(const gchar *filename)
   return TRUE;
 }
 
+static gboolean
+_is_reliable(const gchar *filename)
+{
+  const gsize extension_start = sizeof("syslog-ng-00000") - 1;
```
[the remark this answers is not in the document]
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c]: As this function moved to `qdisk.c` I have modified this to be able to return with error. I have added this check, too.

File: modules/diskq/diskq-global-metrics.c (hunk 1 above)
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c:116]: I have added a check to skip the corrupted files.

File: modules/diskq/diskq-global-metrics.c (hunk 5 above)
Comment (alltilla) [reply modules/diskq/diskq-global-metrics.c]: Yes :/ I have kept it like this.

**Comment by alltilla** [comment]
Rebased to master and fixed all the comments I think. I have not tested it manually yet, but I will do that tomorrow.

**Comment by MrAnno** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

File: modules/diskq/diskq-global-metrics.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (MrAnno) [reply modules/diskq/diskq-global-metrics.c]: Thanks

**Comment by alltilla** [comment]
Tested manually, the behavior looks good to me.

File: lib/stats/stats-registry.c [hunk 9]
```diff
@@ -355,6 +355,15 @@ stats_get_cluster(const StatsClusterKey *sc_key)
...
 
+gboolean
+stats_remove_cluster(const StatsClusterKey *sc_key)
+{
+  g_assert(stats_locked);
+
+  return g_hash_table_remove(stats_cluster_container.dynamic_clusters, sc_key) ||
+         g_hash_table_remove(stats_cluster_container.static_clusters, sc_key);
+}
+
```
Comment (alltilla) [inline lib/stats/stats-registry.c:366]: @MrAnno Should the stats API only allow removing if the cluster is abandoned?

Comment (alltilla) [reply lib/stats/stats-registry.c:366]: Orphaned* ...

Comment (alltilla) [reply lib/stats/stats-registry.c:366]: I will fix this. Is it okay to do in a separate PR, if you find this one good except this?

File: modules/diskq/diskq-global-metrics.h [hunk 10]
```diff
@@ -27,5 +27,7 @@
 
 void diskq_global_metrics_init(void);
```
Comment (MrAnno) [inline modules/diskq/diskq-global-metrics.h:28]: I've checked and thanks to `disk_buffer_module_init()`, global metrics are not initialized when no disk-buffer is used in the configuration. 👍🏻

**Comment by MrAnno** [comment]
I've reproduced a crash:
```
**
ERROR:../modules/diskq/diskq-global-metrics.c:373:diskq_global_metrics_file_acquired: assertion failed: (acquired_files)
Bail out! ERROR:../modules/diskq/diskq-global-metrics.c:373:diskq_global_metrics_file_acquired: assertion failed: (acquired_files)
fish: Job 1, 'sbin/syslog-ng -Fedv' terminated by signal SIGABRT (Abort)
```

Reproduction steps:
-  start syslog-ng with `network(127.0.0.1 port(4444) disk-buffer(dir("/tmp/asd") disk-buf-size(10M)));`
- change dir and reload:  `network(127.0.0.1 port(4444) disk-buffer(dir("/tmp/asd2") disk-buf-size(10M)));`

**Comment by MrAnno** [comment]
The issue persist even after restarts. I was wrong about the persist vs. global metrics diff:
If we open a disk-buffer file in a directory that is recorded in the persist file but not in the configuration, we'll need a force-watch.

File: modules/diskq/diskq-global-metrics.c [hunk 11]
```diff
@@ -63,6 +72,156 @@ _dir_watch_timer_start(DiskQGlobalMetrics *self)
...
+  options.read_only = TRUE;
+
+  LogQueue *queue;
+  if (reliable)
+    queue = log_queue_disk_reliable_new(&options, abs_filename, NULL, STATS_LEVEL0, NULL, NULL);
+  else
+    queue = log_queue_disk_non_reliable_new(&options, abs_filename, NULL, STATS_LEVEL0, NULL, NULL);
+  LogQueueDisk *queue_disk = (LogQueueDisk *) queue;
+
+  if (!log_queue_disk_start(queue))
```
Comment (MrAnno) [inline modules/diskq/diskq-global-metrics.c:116]: This has some `internal()` side effects on the info level:
```
[2023-04-05T11:57:37.812272] Disk-buffer state loaded; filename='/tmp/asd/syslog-ng-00abandoned000.qf', number_of_messages='0'
```

I don't think it's a problem. Please just click "resolve" if you agree.

File: modules/diskq/diskq-global-metrics.c (hunk 1 above)
Comment (MrAnno) [reply modules/diskq/diskq-global-metrics.c:116]: Thank you.

File: lib/stats/stats-registry.c (hunk 9 above)
Comment (MrAnno) [reply lib/stats/stats-registry.c:366]: As you see fit.

**Comment by MrAnno** [comment]
I've found one (hopefully) last thing:

Now that we know that we need to watch (or force-watch) directories coming NOT from the config, but from persisted disk-buffer locations, the following two cases became more valid:
- a directory is removed
  `disk-buffer: Failed to list files in dir; dir='/tmp/asd2', error='No such file or directory (2)'`
  `disk-buffer: Failed to get filesystem info; dir='/tmp/asd2', error='No such file or directory (2)'`
- a file is removed: nothing happens but we don't remove abandoned counters (on reload I think we should)

And a more interesting case; when a new directory is added to the config, but because of the persist file, we still use the old location:
```
[2023-04-05T12:21:41.035721] The disk buffer directory has changed in the configuration, but the disk queue file cannot be moved; qfile='/tmp/asd/syslog-ng-00001.qf', dir='/tmp/asd2'
[2023-04-05T12:21:41.036112] disk-buffer: Failed to get filesystem info; dir='/tmp/asd2', error='No such file or directory (2)'
```

File: lib/stats/stats-registry.c (hunk 9 above)
Comment (alltilla) [reply lib/stats/stats-registry.c]: Fixed.

**Comment by alltilla** [comment]
@kira-syslogng do stresstest

**Comment by alltilla** [comment]
I have loosened an assert in `QDisk`, as I am a bit paranoid that if the file gets emptied by something external in a bad split second, we could fail that assert.

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

**Comment by alltilla** [comment]
@kira-syslogng do stresstest

**Comment by kira-syslogng** [comment]
Kira-stress-test: Build SUCCESS

**Comment by MrAnno** [comment]
I'm investigating a SIGABRT in disk-buffer when config initialization is not successful (I'm not sure this is related to this PR).

File: modules/diskq/qdisk.c [hunk 12]
```diff
@@ -278,6 +290,35 @@ qdisk_get_next_filename(const gchar *dir, gboolean reliable)
...
+{
+  const gsize min_len = MIN(strlen(QDISK_FILENAME_REL_EXAMPLE), strlen(QDISK_FILENAME_NON_REL_EXAMPLE));
+  const gsize prefix_len = strlen(QDISK_FILENAME_PREFIX);
+  const gsize extension_start = strlen(QDISK_FILENAME_PREFIX QDISK_FILENAME_IDX_EXAMPLE);
+
+  gsize len = strlen(filename);
+  if (len < min_len)
+    return FALSE;
+
+  if (strncmp(filename, "syslog-ng-", prefix_len) != 0)
```
Comment (MrAnno) [inline modules/diskq/qdisk.c:304]: Opt: `QDISK_FILENAME_PREFIX`

File: lib/stats/stats-registry.c [hunk 13]
```diff
@@ -355,6 +355,31 @@ stats_get_cluster(const StatsClusterKey *sc_key)
...
+  sc = g_hash_table_lookup(stats_cluster_container.static_clusters, sc_key);
+  if (sc)
+    {
+      if (stats_cluster_is_orphaned(sc))
+        return g_hash_table_remove(stats_cluster_container.static_clusters, sc_key);
+      return FALSE;
+    }
+
+  return FALSE;
```
Comment (MrAnno) [inline lib/stats/stats-registry.c:380]: `return TRUE`

**Review by MrAnno — COMMENTED** [review]
LGTM.

File: lib/stats/stats-registry.c (hunk 13 above)
Comment (MrAnno) [reply lib/stats/stats-registry.c:380]: my bad

Comment (alltilla) [reply lib/stats/stats-registry.c:380]: For reference, this function mimics the return value of https://docs.gtk.org/glib/type_func.HashTable.remove.html#return-value
