### PR TITLE
systemd-journal: fix --with-systemd-journal=optional mode

### LINKED ISSUE #4300: Dynamic loading of journald symbols fails
# syslog-ng
## Version of syslog-ng
syslog-ng 4 (4.0.1.96.g1635664)

## Platform
Ubuntu 22.04.1 LTS
debian-buster_amd64
oracle-7_amd64
sles-12_amd64
ubuntu-xenial_amd64
rhel-7_amd64

# Issue
syslog-ng crashes during loading of module='sdjournal'

## Failure

[2023-02-01T14:08:20.879032] Module loaded and initialized successfully; module='system-source'
[2023-02-01T14:08:20.879074] Trying to open module; module='sdjournal', filename='/home/test/Develop/syslog-ng/build/install/lib/syslog-ng/libsdjournal.so'

Program received signal SIGSEGV, Segmentation fault.
0x0000fffff7a9162c in g_module_symbol () from /lib/aarch64-linux-gnu/libgmodule-2.0.so.0
(gdb) bt
#0  0x0000fffff7a9162c in g_module_symbol () from /lib/aarch64-linux-gnu/libgmodule-2.0.so.0
#1  0x0000fffff708a6d4 in _load_journald_symbols () at ../modules/systemd-journal/journald-subsystem.c:79
#2  0x0000fffff708aa80 in load_journald_subsystem () at ../modules/systemd-journal/journald-subsystem.c:145
#3  0x0000fffff70879cc in systemd_journal_module_init (context=0xaaaaaaad5a40, args=0x0) at ../modules/systemd-journal/systemd-journal-plugin.c:44
#4  0x0000fffff7ecc8b0 in plugin_load_module (context=0xaaaaaaad5a40, module_name=0xaaaaaaae9e80 "sdjournal", args=0x0) at ../lib/plugin.c:405
#5  0x0000fffff7ecc628 in plugin_find (context=0xaaaaaaad5a40, plugin_type=3, plugin_name=0xaaaaaac1e630 "systemd-journal") at ../lib/plugin.c:337
#6  0x0000fffff7e9d904 in cfg_find_plugin (cfg=0xaaaaaaad5a30, plugin_type=3, plugin_name=0xaaaaaac1e630 "systemd-journal") at ../lib/cfg.c:239
#7  0x0000fffff7ede20c in main_parse (lexer=0xaaaaaabb71b0, dummy=0xffffffffedb8, arg=0x0) at ../lib/cfg-grammar.y:547
#8  0x0000fffff7ea40fc in cfg_parser_parse (self=0xfffff7fab020 <main_parser>, lexer=0xaaaaaabb71b0, instance=0xffffffffedb8, arg=0x0) at ../lib/cfg-parser.c:408
#9  0x0000fffff7e9e628 in cfg_run_parser (self=0xaaaaaaad5a30, lexer=0xaaaaaabb71b0, parser=0xfffff7fab020 <main_parser>, result=0xffffffffedb8, arg=0x0) at ../lib/cfg.c:596
#10 0x0000fffff7e9e94c in cfg_read_config (self=0xaaaaaaad5a30, fname=0xaaaaaaabcac0 "/home/test/Develop/syslog-ng/build/install/etc/syslog-ng.conf", preprocess_into=0x0) at ../lib/cfg.c:683
#11 0x0000fffff7ec2990 in main_loop_read_and_init_config (self=0xfffff7fae320 <main_loop>) at ../lib/mainloop.c:618
#12 0x0000aaaaaaaa263c in main (argc=1, argv=0xffffffffefd8) at ../syslog-ng/main.c:307

## Steps to reproduce
configure and build syslog-ng with **--with-systemd-journal=optional** switch than start it with the default configuration

## Configuration
default (that uses system journald)

By a good chance this issue is related to changes of #4245

### PR DESCRIPTION
**Pull request by bazsi**
This patch fixes #4300 that was a regression from #4225.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

File: modules/systemd-journal/journald-subsystem.h [hunk 1]
```diff
@@ -65,25 +65,44 @@ union sd_id128
...
+ *
+ * By using "hidden" visibility, we tell the linker that these symbols are
+ * internal to the current .so, meaning that any code that references these
+ * from this module will happily use these as pointers while other modules
+ * of syslog-ng can still use them as functions.
+ *
+ * See https://github.com/syslog-ng/syslog-ng/issues/4300 for more details.
+ */
+
+#define VISIBILITY_HIDDEN __attribute__((visibility("hidden")))
```
Comment (HofiOne) [inline modules/systemd-journal/journald-subsystem.h:85]: this is what I was looking for after I realized that **g_module_symbol** finds the given symbol in our plugin first not in the module passed as its first parameter that is, in my opinion, a glib bug

**Review by HofiOne — APPROVED** [review]
