### PR TITLE
accepting longer sdata keys

### LINKED ISSUE #3197: SDATA key > 32 characters is malformed
# syslog-ng
## Version of syslog-ng
root@system-test:/tmp # syslog-ng --version
syslog-ng 3 (3.25.1)
Config version: 3.25
Installer-Version: 3.25.1
Revision: 
Compile-Date: Mar 11 2020 05:16:25
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Include-Path: /usr/local/share/syslog-ng/include
Available-Modules: json-plugin,appmodel,cef,syslogformat,add-contextual-data,timestamp,disk-buffer,afsocket,affile,afprog,afuser,csv
parser,confgen,examples,system-source,linux-kmsg-format,basicfuncs,dbparser,cryptofuncs,afstomp,pseudofile,graphite,kvformat,map-val
ue-pairs,snmptrapd-parser,stardate,tfgetent,tags-parser,xml,hook-commands,http
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off

## Platform
root@system-test:/tmp # uname -a
FreeBSD system-test 11.2-RELEASE-p14 FreeBSD 11.2-RELEASE-p14 #0: Mon Aug 19 22:38:50 UTC 2019     root@amd64-builder.daemonology.net:
/usr/obj/usr/src/sys/GENERIC  amd64

## Debug bundle
Not Available

# Issue
## Failure
Syslog-ng mangles SDATA PARAM-NAME when the PARAM-NAME is longer than 32 characters.  If I only change the PARAM-NAME to be shorter than 32 chars (leaving the JSON key the same at longer than 32 chars) parsing is completed successfully.

## Steps to reproduce
Send SDATA PARAM with PARAM-NAME longer than 32 characters.

## Configuration
**syslog-ng.conf**
```
@version: 3.25

source s_json_file {
    file("/tmp/full_log.txt" flags(syslog-protocol));
};

destination d_file {
    file("/tmp/in-out.log" flags(syslog-protocol));
};

parser p_json {
    json-parser(prefix(".event"));
};

log {
    source(s_json_file);
    parser(p_json);
    # Write messages in syslog protocol
    destination(d_file); 
};
```

## Input and output logs (if possible)

**Input File with Long PARAM-NAME**
```
<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long_Field_N
ame_Right_here="longKey"] {"EventReceivedTime"="2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here"="longKey"}
```

**Command Ran and Error Received**
```
root@system-test:/tmp # syslog-ng -Fdev -c /usr/local/etc/syslog-ng.conf -R /tmp/syslog-ng.persist

[...]

[2020-03-25T14:12:18.818010] syslog-ng starting up; version='3.25.1'
[2020-03-25T14:12:18.818218] Running application hooks; hook='2'
[2020-03-25T14:12:18.818659] Incoming log entry; line='<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long_Field_Name_Right_here="longKey"] {"EventReceivedTime"="2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here"="longKey"}'
[2020-03-25T14:12:18.818981] json-parser(): failed to parse JSON payload; input='Error processing log message: <13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long_Field_Name_Right_he>@<re="longKey"] {"EventReceivedTime"="2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here"="longKey"}', json_error='unexpected character'
```

---

**Input File with PARM-NAME Less Than 32 Chars**
```
<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKe
y"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}
```

**Command Ran and Debug Output Showing No Errors**
```
root@system-test:/tmp # syslog-ng -Fdev -c /usr/local/etc/syslog-ng.conf -R /tmp/syslog-ng.persist

[...]

[2020-03-25T14:34:06.292977] syslog-ng starting up; version='3.25.1'
[2020-03-25T14:34:06.293079] Running application hooks; hook='2'
[2020-03-25T14:34:06.293425] Incoming log entry; line='<13>1 2020-03-02T05:30:11.293419-06:00 HOSTNAME program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKey"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}'
[2020-03-25T14:34:06.293981] Initializing destination file writer; template='/tmp/in-out.log', filename='/tmp/in-out.log'
[2020-03-25T14:34:06.294262] Outgoing message; message='<13>1 2020-03-02T05:30:11-06:00 system-test program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKey"][meta sequenceId="1"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}\x0a'
```

**Output File with PARAM-NAME less than 32 Chars**
```
root@system-test:/tmp # cat in-out.log 
<13>1 2020-03-02T05:30:11-06:00 system-test program - - [NXLOG@14506 EventReceivedTime="2020-03-02 05:30:11" Really_Long="longKey"][me
ta sequenceId="1"] {"EventReceivedTime":"2020-03-02 -5:30:11", "Really_Long_Field_Name_Right_here":"longKey"}
```

### PR DESCRIPTION
**Pull request by szemere**
While the RFC5424 states that the maximum length for the SD-ID and PARAM-NAME fields is 32 characters. It also states that a syslog relay should forward messages, even if the SDATA is mailformed.

With this patch, syslog-ng will accept SDATA fields longer than 32 characters, using the message size as the upper limit.

Fixes #3197

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by szemere** [comment]
@kira-syslogng do perftest

(Travis finished successfully, it is only a synchronization error with GitHub.)

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build SUCCESS

File: modules/syslogformat/syslog-format.c [hunk 1]
```diff
@@ -567,21 +568,12 @@ log_msg_parse_sd(LogMessage *self, const guchar **data, gint *length, const MsgF
...
-                  if (isascii(*src) && *src != '=' && *src != ' ' && *src != ']' && *src != '"')
-                    {
-                      sd_id_name[pos] = *src;
-                      pos++;
-                    }
-                  else
-                    {
-                      goto error;
-                    }
+                  g_string_append_c(sd_id_name, *src);
```
Comment (bazsi) [inline modules/syslogformat/syslog-format.c:576]: with this change, we are removing any limits from the name of SDATA elements, which might be fine on its own, however we have a 255 limit on the length of name-value names

https://github.com/syslog-ng/syslog-ng/blob/04d68db1617b64a2458baee3caefe68df28830c1/lib/logmsg/nvtable.c#L65

Increasing that is a lot more difficult, as we are using a guint8 value to represent the length in NVTable (which is also serialized to disk).

So I would stick to static limits here, instead of using scratch buffers. Might also be good for performance.

I'd recommend a max size of 255 characters for each component and truncate the concatenated value at 255, this way we would still retain the name-value pair, albeit with a truncated name.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@szemere : is it still WIP?

File: modules/syslogformat/syslog-format.c [hunk 2]
```diff
@@ -21,6 +21,8 @@
  *
  */
 
+#include <stdio.h>
```
Comment (bazsi) [inline modules/syslogformat/syslog-format.c:24]: I think we don't need this.

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: tests/unit/test_msgparse.c [hunk 3]
```diff
@@ -204,29 +204,6 @@ run_parameterized_test(struct msgparse_params *params)
     test_log_messages_can_be_parsed(param);
 }
 
-Test(msgparse, test_failed_to_parse_too_long_sd_id)
```
Comment (furiel) [inline tests/unit/test_msgparse.c:207]: This test should not be deleted. Instead, let's update to use longer SD-NAME.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by furiel — APPROVED** [review]

**Review by gaborznagy — APPROVED** [review]
