### PR TITLE
gprocess: fix macOS compatibility

### LINKED ISSUE #3385: syslog-ng compiles but fails to start on macOS Big Sur
It is possible to compile syslog-ng on the latest macOS beta. But when trying to start it, I get an error message:
```
bash-3.2# /usr/local/sbin/syslog-ng -Fvde
iv_fd_register: called with invalid fd 6 (maxfd=-1)
Abort trap: 6
bash-3.2#
```
Based on the above error message the problem might be in ivykis. I use ivykis from brew (which works perfectly on the latest stable macOS).
```
Peters-MacBook-Pro:~ czanik$ brew info ivykis
ivykis: stable 0.42.4 (bottled)
Async I/O-assisting library
https://sourceforge.net/projects/libivykis/
/usr/local/Cellar/ivykis/0.42.4 (88 files, 230.0KB) *
  Poured from bottle on 2020-08-10 at 16:06:25
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ivykis.rb
License: LGPL-2.1
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔
==> Analytics
install: 22 (30 days), 47 (90 days), 142 (365 days)
install-on-request: 23 (30 days), 48 (90 days), 143 (365 days)
build-error: 0 (30 days)
```

### PR DESCRIPTION
**Pull request by MrAnno**
man `setrlimit()`:
> It no longer accepts "rlim_cur = RLIM_INFINITY" for RLIM_NOFILE.
> Use "rlim_cur = min(OPEN_MAX, rlim_max)".

Note:
I could have used `sysconf()` to get `OPEN_MAX` in a portable manner, like this:
https://github.com/syslog-ng/syslog-ng/blob/013df12e397eb3bfc40d00f0c1b7cb228d28483f/modules/affile/directory-monitor.c#L57

but I think it's not necessary in this case, as `rlim_cur` can be set to `rlim_max` on all platforms except for macOS.

Fixes #3385.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

File: lib/gprocess.c [hunk 1]
```diff
@@ -683,7 +683,13 @@ g_process_change_limits(void)
   struct rlimit limit;
 
   getrlimit(RLIMIT_NOFILE, &limit);
+
+#if defined(__APPLE__) && defined(__MACH__)
+  limit.rlim_cur = MIN(OPEN_MAX, limit.rlim_max);
```
Comment (Kokan) [inline lib/gprocess.c:688]: Optional: a warning/info msg might be nice to have here, if the `OPEN_MAX` is less then `limit.rlim_max`.

Comment (MrAnno) [reply lib/gprocess.c:688]: `rlim_max` is infinity by default, so the warning would be produced in most cases.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
The PR also fixes the macOS GitHub Actions job.
It seems GitHub runners have Python 2 preinstalled, which prevents brew symlinking Python 3.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Review by Kokan — APPROVED** [review]

**Review by gaborznagy — APPROVED** [review]
